### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#11]
Followup to discussion in https://github.com/davidtheclark/cosmiconfig/issues/9:

- js (default `true`): if `false`, don't look for `modulename.config.js`.
- rc (default: `true`): if `false, don't look for `.modulenamerc`.
- packageProp (default: `true`): if `false`, don't look for property `modulename` in `package.json` files.
- argv (default: `true`): if `false`, don't look for `--config` arguments

**Comment by TrySound** [comment]
@davidtheclark I don't like strictJSON idea. I'm for simple parsing. rc by yaml, .json by parse-json etc

**Comment by davidtheclark** [comment]
It really bugs me that js-yaml parses bogus JSON; but unless I can figure out a better way of determining whether an rc file is intended to be parsed as JSON or YAML, I guess we probably need to go with your plan.

**Comment by davidtheclark** [comment]
I guess we could have an option `rcJsOnly: Boolean`, so if a project wants to only permit strict JSON config they could flip the switch.

**Comment by TrySound** [comment]
Yeah, it can be, but maybe better rcJsonOnly

**Comment by davidtheclark** [comment]
Oh yep, that was a typo.

**Comment by TrySound** [comment]
Or rcStrictJSON

**Comment by davidtheclark** [comment]
If ended up combining `rcName` and `jsName` with the new `rc` and `js` options, and including `rcStrictJson`.
