### ISSUE TITLE
Support for config modules

### ISSUE THREAD

**Issue by orta** [davidtheclark/cosmiconfig#110]
Hello there, love your work here. 

I've been wanting to try and move some of my default config settings into a module. Given that a chunk of my fav tools are already using cosmiconfig, I wondered if adding support into this module would be a great way to take a stab at this.

For example, I normally add 

```json
  "prettier": {
    "printWidth": 120,
    "semi": false,
    "singleQuote": false,
    "trailingComma": "es5",
    "bracketSpacing": true
  },
```

To every repo's `package.json`. 

In an ideal world I could create a module called `cosmiconfig-orta` which would contain either:

* a `package.json` with the prettier key
* a `prettierrc`

Then prettier would use those settings instead of me needing to add them to each repo.  Meaning I can keep both the locked dependencies and their config in a single module. 

--- 

Side note: I'm happy to implement this.

**Comment by sudo-suhas** [comment]
Hey @orta, could you elaborate on how the proposed feature would be used by the end-user(like what would be the `cosmiconfig` options)? Is it similar to how eslint shared configs work? eslint shared config work do not support package.json property or an rc file though.

**Comment by orta** [comment]
An end-user would create a module, push it, then for every project they would just need to run `yarn add cosmiconfig-orta --dev` and each of those projects would pick up that settings are inside that module.

I'd expect it to be last on the prioritization list, e.g. section of `package.json`, `${module}rc`, search node_modules for `cosmiconfig-*`.  This would mean I could consolidate the config for prettier, eslint, husky, semantic-release etc inside a single module.

If the module is found then it could run the same checks it runs in the current working dir  ( `package.json`, `${module}rc`, etc ) giving you the ability to just move a bunch of files into a module and shipping it.

**Comment by sudo-suhas** [comment]
I don't think that'd work. With deduping and flattening, there is a high probability of multiple such modules being present in the `node_modules` folder.

**Comment by orta** [comment]
I disagree, you'd only put it in once in a project at the root and it wouldn't be included as a dependency of another project.

**Comment by sudo-suhas** [comment]
Oh right.. Cause it's a dev dependency. I'll let @davidtheclark take a call on this though. Seems a bit too magical to me :sweat_smile:

**Comment by orta** [comment]
I took a look at roughly implementing this, didn't finish, but there are two ways of building it that I could see:

* Add support for a new `cosmiconfig` option inside the cwd's `package.json` which can have a reference to the module. This could allow any named module, and is very explicit. e.g.:

  ```json
  {
    "name": "cocoapods-decocoadocs",
    "version": "0.0.0",
    "description": "A web server for CocoaPods stats",
    "main": "index.js",
    "cosmic": {
      "config": "orta-config"
    }
  }
  ```

* Look inside the devDependenciess of the package.json for a `cosmiconfig-x` and then use that, which is more about convention over config

  ```json
  {
    "name": "cocoapods-decocoadocs",
    "version": "0.0.0",
    "description": "A web server for CocoaPods stats",
    "main": "index.js",
    "devDependencies": {
      "cosmiconfig-orta": "^0.0.1"
    }
  }
  ```

**Comment by davidtheclark** [comment]
@orta I really like the idea. I would love to have something like this myself — a single npm package that would include the eslint, prettier, husky, lint-staged, stylelint, remark-lint, etc. configs that I reproduce repeatedly.

However, I don't think that's within the scope of cosmiconfig. Cosmiconfig is a low-level tool and each of the dependent projects, like Prettier, actually determine their own configuration API. Prettier needs to decide upon and document how the user configures it — then Prettier can use cosmiconfig behind the scenes to enable that pattern. The dependent gets to decide which of cosmiconfig's features it uses; and if the dependent package decides to drop cosmiconfig to load its config in some other way, the end user shouldn't be disturbed by that move.

It seems to me that this proposal would slide behind the public APIs documented by dependents like Prettier. We can't make that decision for dependents, though; we can't provide a feature that would encourage end users to load config for some dependent in a way that is not what that dependent deliberately chose.

So I think this idea should be brought up a level, to the packages that end users install, like Prettier, stylelint, etc. If they want to band together and provide a *new* way of loading configuration that enables these configuration-bundle packages, that's up to them. (And I think they could probably accomplish this already by pointing cosmiconfig in the right direction.)

**Comment by sudo-suhas** [comment]
What do you think of this? A package which copies over config files in a post install hook or through a command(`./node_modules/.bin/cfg-mgr refresh`)? By looking at the currently installed packages, the necessary config files could be added to the project root.

**Comment by orta** [comment]
Could this instead be added as an exposed function somehow from cosmiconfig, so that adding support for the clients is a single liner?

**Comment by chiptus** [comment]
why not just use and `extend` key like in eslint? see https://eslint.org/docs/developer-guide/shareable-configs

**Comment by orta** [comment]
That is likely custom code in eslint. 

My aim in this issue is to have a way to make it so that all of the projects using cosmiconfig could have _something_ where you define that extend key once and have it apply to all config consumers. Otherwise you still have configs everywhere, but each has to build the extends feature, and you still have to have configs that set the extends value.

**Comment by chiptus** [comment]
I would say it's logical to require having a .prettierrc in every project,
how else would you know it's using prettier?

**Comment by orta** [comment]
I can't tell if you're trolling, but you can determine it by either looking for the keys in the package.json or if it's in node_modules. I try keep as many settings as possible in package.json. I'm not quite sure how that really is relevant though?
