### ISSUE TITLE
Provide searchSync and loadSync functions, instead of the sync option

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#112]
I was [reviewing the documentation](https://github.com/davidtheclark/cosmiconfig/pull/111), then poking around in the code a little bit, wondering if things could be simplified —— and I'm thinking that the challenges we have in documenting and Flow-typing functions, because they can be sync or async based on an option, indicates a flaw that we should refactor out.

Instead of the `sync` option, we could have `explorer.searchSync` and `explorer.loadSync` functions. Internally, we'd do the same thing with our utility functions. I believe that the standard practice across Node is to provide separate functions for sync and async versions of the same behavior — instead of overloading a single function. This results in each function having a cleaner signature, which is easier to document, type check, unit test.

Does anybody object? If not, I will work on this refactoring and the new functions before our v5 release.

**Comment by olsonpm** [comment]
yeah that would follow node's approach (and thus others, since most libs I work with have a `*Sync` alternative.  big :+1:

**Comment by olsonpm** [comment]
fyi - I think this implies a new option `transformSync`.

**Comment by olsonpm** [comment]
yeah I thought a little about a clean approach - came up empty.  What you suggest sounds good to me as I also don't like the idea of two separate transform options.

**Comment by sudo-suhas** [comment]
I too like the idea of having separate functions for the sync and async version. But should it be `searchSync` or `search.sync`? I have seen this pattern in various places including [`is-directory`](https://github.com/jonschlinkert/is-directory).

**Comment by davidtheclark** [comment]
> But should it be searchSync or search.sync?

I believe that the reason libraries go with `fn` (async) and `fn.sync` is because of how CommonJS works: that way the module can have one main export, the default function that people should use most of the time, instead of exporting an object. So you get `fn` and `fn.sync` instead of `SomeModule.fn` and `SomeModule.fnSync`.

That situation doesn't apply to us, so I favor the `searchSync` convention.

**Comment by sudo-suhas** [comment]
That makes sense @davidtheclark. Thanks for explaining.

**Comment by davidtheclark** [comment]
#120 introduced the functions, but we still need a pass at documentation.

**Comment by davidtheclark** [comment]
Documented now in the v5 branch.
