### ISSUE TITLE
Feat: use JSON5 instead of JSON.parse for friendly JSON syntax

### ISSUE THREAD

**Issue by imcuttle** [davidtheclark/cosmiconfig#119]
[json5](https://github.com/json5/json5)

```js
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```

**Comment by olsonpm** [comment]
i think there's work toward using `require` instead of parsing the file as a string.  We'll then allow consumers to pass their own require function.  This is mainly to support es modules but your use-case will be covered here as well.

Anyway we can leave this issue open till that's finished

**Comment by sudo-suhas** [comment]
@olsonpm That would apply for JS file only right? Or are we allowing override for other file types as well?

**Comment by olsonpm** [comment]
why we wouldn't require json files?

**Comment by sudo-suhas** [comment]
Because the errors in the default case would not be very helpful. Which is why we use [`parse-json`](https://github.com/sindresorhus/parse-json) right now.

**Comment by olsonpm** [comment]
but requiring would be a lot more friendly toward parsing other flavors of json while keeping the options fewer and thus api cleaner.  How would you choose to handle other flavors of json?

**Comment by sudo-suhas** [comment]
That hasn't really come up until now. Moreover, YAML allows greater flexibility for defining a config file including comments, skipping double-quotes etc. And as I mentioned, I think the default case is more important.

**Comment by olsonpm** [comment]
Yeah I guess I just figured we would require given davidtheclark introduced it as the mechanism for parsing js files - it seems natural to me to also require json files e.g. `const { version } = require('./package.json')`.  Personally I would find json5 more palatable than yaml given it's more familiar.  I'm not a fan of whitespace sensitive syntaxes, and although I understand why they didn't support comments in vanilla json, comments are extremely useful in a lot of circumstances.

@davidtheclark - any thoughts on whether to support json5? and what implementation you'd prefer.

**Comment by davidtheclark** [comment]
I was not planning on using `require` for JSON files. I don't think there's a need.

I am not interested in going down a rabbit hole to support "other flavors of json". [The request to parse multiple flavors of JS](https://github.com/davidtheclark/cosmiconfig/issues/109) opens the door to more than enough flexibility, I think. And YAML provides opportunity for comments outside of JS files.

If there's some strong argument about why JSON5 is a superior config format in common situations, not just be an arbitrary personal preference, I'd consider reopening this issue.

**Comment by davidtheclark** [comment]
@imcuttle With v5, you can do this! Provide your own JSON5 loader function, and your users can write JSON5 configs.

**Comment by theKashey** [comment]
json5 is used for tsconfig.json as well as it was used for tslint - https://github.com/microsoft/TypeScript/issues/12242
