### ISSUE TITLE
Add appveyor CI and get Windows build passing

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#12]
Followup to discussion in https://github.com/davidtheclark/cosmiconfig/issues/9.

Add appveyor testing alongside Travis.

**Comment by davidtheclark** [comment]
@MoOx, @TrySound: Have you ever encountered problems like this on appveyor (or Windows generally)? http://stackoverflow.com/questions/33715296/why-is-powershell-erroring-after-successful-tap-tests

**Comment by MoOx** [comment]
I recently got the same problem on statinamic. If you check my commit history, you will find the answer (tl;dr dont use powershell for tests, only cmd, check out statinamic travis.yml).

**Comment by MoOx** [comment]
Powershell can fail with npm warnings and any warnings that is not a failure (eg: babel 100kb warning)

**Comment by davidtheclark** [comment]
I thought you might have the answer. Thanks!

**Comment by davidtheclark** [comment]
Passing now.
