### ISSUE TITLE
Configurable JS Extensions

### ISSUE THREAD

**Issue by shellscape** [davidtheclark/cosmiconfig#122]
In concert with #109 there's probably going to be a call for configuring what valid "js" extensions are. For example, [esm](https://github.com/standard-things/esm) and Node itself to some degree, are recommending using `.mjs`. If the `parseJs` option, or something like it, comes to fruition, we're going to be able to handle TypeScript, ESM, etc.

Would this addition be welcome on the v5 branch? I'd be happy to submit a PR, but would like to know it's something viable before I put the time in.

**Comment by davidtheclark** [comment]
Yep, I guess we should add this option.

**Comment by davidtheclark** [comment]
How about `jsExtensions: Array<string>`, defaulting to `['js']`. We'll loop through the `jsExtensions` and look for a file corresponding to each one. If you need fancy parsing for some extensions, you'll need to provide a `loadJs` function (as discussed for v5 in #109) that looks at the file path and decides what to do from there. 

@shellscape: Does that API sound like it will work?

**Comment by shellscape** [comment]
@davidtheclark yeah that sounds good to me

**Comment by davidtheclark** [comment]
In the v5 branch, this can now be accomplished by using a combination of `searchPlaces` and `loaders`. 

@shellscape I think I recall that you want to use `require` hooks, right? If that's the case, you can use the regular JS loader for all the JS-like files you want, e.g.:

```js
{
  searchPlaces: [
    'someting.config.js',
    'someting.config.mjs',
    'someting.config.ts',
  ],
  // Specify how to load the special extensions.
  // loadJs just uses require
  loaders: {
    mjs: cosmiconfig.loadJs,
    ts: cosmiconfig.loadJs,
  }
}
```
