### ISSUE TITLE
.modulerc.js not supported in v5

### ISSUE THREAD

**Issue by hudochenkov** [davidtheclark/cosmiconfig#144]
I've noticed that in v5 support for config named as `.modulerc.js` is not enabled by default. There is no clear indication about this in the changelog. Is this change intentional?

**Comment by sudo-suhas** [comment]
This might have been an oversight. However, it should be very easy to add support for  this by passing in the `searchPlaces` option for `createExplorer`. That said, this might be a sensible default to support loading `.modulerc.js`. @davidtheclark, @olsonpm What are your thoughts on this?

**Comment by olsonpm** [comment]
I'm working on a PR

**Comment by davidtheclark** [comment]
Fix released in 5.0.4.

**Comment by hudochenkov** [comment]
Thank you for a quick fix!
