### ISSUE TITLE
require cache can mess with JS file-loading in tests

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#148]
See https://github.com/davidtheclark/cosmiconfig/pull/147/files#r189721953

Because we're now using `require`, it makes sense that the require cache could get in our way for testing.

This may be as simple as using `jest.resetModules()`?

**Comment by chrisblossom** [comment]
We are already using [``jest.resetModules()``,](https://github.com/davidtheclark/cosmiconfig/blob/f849e51123f623d6f32b3073c62e9acbc6ffcebe/package.json#L77) BUT maybe it has the same issue as https://github.com/facebook/jest/issues/6059.



@evocateur can you please provide the steps to reproduce the error you were getting?

**Comment by davidtheclark** [comment]
We could also try a different approach, like https://github.com/sindresorhus/clear-module, to verify that Jest isn't behaving as expected.

**Comment by evocateur** [comment]
From a fresh clone, yarn 1.6.0, node 8.11.1, `yarn && yarn test` was sufficient to reproduce the snapshot error.

**Comment by chrisblossom** [comment]
@evocateur Does it happen every time? Following those steps I am not getting an error working off of [git tag 5.0.4](https://github.com/davidtheclark/cosmiconfig/tree/5.0.4). Can you paste the results of `npx envinfo --preset jest` (this is what jest uses to get basic env info)?

**Comment by sudo-suhas** [comment]
> Does it happen every time? Following those steps I am not getting an error working off of git tag 5.0.4. 

Me too. To be clear, does this issue concern only tests?

**Comment by olsonpm** [comment]
he said it happened semi-randomly

**Comment by evocateur** [comment]
I won’t be able to re-run in the shell I experienced it with until tomorrow morning. I _may_ have been using node v10, I’ve been hopping around via nvm between v8 and v10 lately. I was definitely using yarn latest.

**Comment by sudo-suhas** [comment]
Ran the tests several time with cosmiconfig on 📦 v5.0.4 via ⬢ Node.js v10.1.0  but error could not be reproduced.

**Comment by evocateur** [comment]
```
$ npx envinfo --preset jest
npx: installed 1 in 1.965s

  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.11.1 - ~/.sprinter/zillow/features/nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.6.0 - ~/.sprinter/zillow/features/nvm/versions/node/v8.11.1/bin/yarn
    npm: 5.8.0 - ~/.sprinter/zillow/features/nvm/versions/node/v8.11.1/bin/npm
  npmPackages:
    jest: ^21.2.1 => 21.2.1 
```
```
$ echo $BASH_VERSION
4.4.19(1)-release
```

The funky binary paths are just artifacts of an internal bootstrapping tool, it's functionally an installation of [`nvm`](https://github.com/creationix/nvm) as far as the node.js stuff is concerned.

Not even pulling from upstream, just going back to my fork's `HEAD` (f849e51), `yarn test` immediately repros for me. Here's the relevant logging and error:

```
$ jest --coverage
 PASS  test/successful-files.test.js
 FAIL  test/successful-directories.test.js
  ● works fine if sync loader returns a Promise from a JS file › sync

    expect(received).toEqual(expected)
    
    Expected value to equal:
      {"config": Any<Promise>, "filepath": "/private/var/folders/9s/95tsbq5j12s5yqgxqp8cqb540000gp/T/cosmiconfig/test/successful-directories.test.js-dir/a/b/c/d/e/f/foo.config.js"}
    Received:
      {"config": {"found": true}, "filepath": "/private/var/folders/9s/95tsbq5j12s5yqgxqp8cqb540000gp/T/cosmiconfig/test/successful-directories.test.js-dir/a/b/c/d/e/f/foo.config.js"}
    
    Difference:
    
    - Expected
    + Received
    
      Object {
    -   "config": Any<Promise>,
    +   "config": Object {
    +     "found": true,
    +   },
        "filepath": "/private/var/folders/9s/95tsbq5j12s5yqgxqp8cqb540000gp/T/cosmiconfig/test/successful-directories.test.js-dir/a/b/c/d/e/f/foo.config.js",
      }
      
      at Object.test (test/successful-directories.test.js:1042:20)
          at new Promise (<anonymous>)
          at <anonymous>

 PASS  test/caches.test.js
 PASS  test/failed-directories.test.js
 PASS  test/failed-files.test.js
 PASS  test/index.test.js
 PASS  test/getDirectory.test.js

Test Suites: 1 failed, 6 passed, 7 total
Tests:       1 failed, 159 passed, 160 total
Snapshots:   0 total
Time:        1.26s
Ran all test suites.
-------------------|----------|----------|----------|----------|-------------------|
File               |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------|----------|----------|----------|----------|-------------------|
All files          |      100 |      100 |      100 |      100 |                   |
 cacheWrapper.js   |      100 |      100 |      100 |      100 |                   |
 createExplorer.js |      100 |      100 |      100 |      100 |                   |
 getDirectory.js   |      100 |      100 |      100 |      100 |                   |
 index.js          |      100 |      100 |      100 |      100 |                   |
 loaders.js        |      100 |      100 |      100 |      100 |                   |
 readFile.js       |      100 |      100 |      100 |      100 |                   |
-------------------|----------|----------|----------|----------|-------------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn jest --coverage --no-cache` yields the same error. It's now happening **every** time I run `yarn test` or `yarn jest`.

@chrisblossom `jest.resetModules()` inside the top-level `afterEach()` made no difference.

**Comment by evocateur** [comment]
Oh for glob's sake... `rm -rf node_modules && yarn` and now `yarn test` passes every time...

So my hypothesis right now is that I initially did not have an up-to-date yarn (1.5.0), and my first `yarn` after cloning might have introduced a bad resolution or something? I've become so accustomed to `npm ci` nuking `node_modules`, it didn't even occur to me to distrust a subsequent `yarn` (after upgrading) insisting "already up-to-date".

I still feel that multiple tests using the same temporary directory with the exact same subdirectory paths is asking for trouble, but I can't provide any direct proof in this instance so you might as well close this issue.

Thanks again for the speedy turnaround on my original PR.

**Comment by davidtheclark** [comment]
Since we haven't seen any other reports of this problem and it sounds like the problem has resolved itself, let's close the issue. If something similar arises in the future, we'll address it then.
