### ISSUE TITLE
Load cosmiconfig own options the same way it does for the other modules

### ISSUE THREAD

**Issue by Roms1383** [davidtheclark/cosmiconfig#151]
Hi ! :)
Wouldn't it be nice to have `cosmiconfig` load its own options (a.k.a `cosmiconfigOptions`) in exactly the same way as it does for the modules ?
This way `cosmiconfigOptions` could be set via a :
*  `.cosmiconfig`
*  `.cosmiconfigrc`
*  `.cosmiconfigrc.json`
and so on...
Of course, looking at the implementation it appears that `packageProp` might not be a good candidate for overriding.
That would allow for all packages that upgrade `cosmiconfig` with this feature to allow their user to load their configuration by overriding `searchFrom` for example to look for their config in a sub-directory (instead of up the directory tree, which can be more convenient especially in a CI environment), instead of waiting that each modules which use `cosmiconfig` exposes a way to do so.
Thanks for your feedback on it, I quickly looked at the implementation I might have overlooked something, but it seems doable.

**Comment by davidtheclark** [comment]
Hi @Roms1383. Interesting idea. I think, though, that the decision to do something like this should be in the hands of cosmiconfig's consumers, not cosmiconfig itself. If a program using cosmiconfig wants to do something like this, I believe they can with the interface cosmiconfig already exposes. But I think that cosmiconfig is not going to make those decisions *for* the consumer programs.

**Comment by olsonpm** [comment]
Thanks for the explanation.  I couldn't wrap my head around the use-case and so didn't know how to respond.
