### ISSUE TITLE
RFC Config directory

### ISSUE THREAD

**Issue by jish** [davidtheclark/cosmiconfig#154]
I would like to add a new configuration option to search for files in a specified configuration directory. In the documentation for `searchPlaces` this is given as the last example:

https://github.com/davidtheclark/cosmiconfig/blob/master/README.md#searchplaces

```js
{
  searchPlaces: [
    '.porgyrc',
    '.config/.porgyrc',
    '.porgyrc.json',
    '.config/.porgyrc.json'
  ]
}
```

I propose adding a new option (maybe `configDir`, `configurationDirectory` or something similar?) that would automate this process, and make the options more concise:

```js
{
  configDir: 'config',
  searchPlaces: [
    '.porgyrc',
    '.porgyrc.json'
  ],
}
```

What do you think?

**Comment by davidtheclark** [comment]
Hi @jish. As you note, this is already possible using `searchPlaces`, and I tried to deliberately design that API to allow for full flexibility with a relatively simple configuration. I think that the second example in your comment is not a significant enough simplification that I want to go to the trouble of expanding the library's API for it.

Also, I'm not sure how much this would get used. If there's a cosmiconfig-using tool that you'd like to configure from a `.config/` directory, you could file a feature request with that tool — or contribute a PR. If enough cosmiconfig users end up requesting the same new default, we can consider changing it here. But at this point I don't think I want to use cosmiconfig's defaults to sneak new conventions into other tools: I'd rather leave those choices to the tools themselves.

Thanks for the idea.
