### ISSUE TITLE
Alternative to 'import * as' module syntax

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [davidtheclark/cosmiconfig#159]
This is no longer valid JavaScript:

```javascript
import * as cosmiconfig from 'cosmiconfig';

cosmiconfig('module-name');
```

https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this/39415662#39415662

> An ES6 module namespace object cannot be invoked as a function or with new.
> The thing you import using * as X from a module is defined to only have properties.

As a backwards-compatible change, this module should have something like this added at the bottom of `src/index.js`:

```javascript
cosmiconfig.cosmiconfig = cosmiconfig;
```

That way we'll be able to do this:

```javascript
import { cosmiconfig } from 'cosmiconfig';

cosmiconfig('module-name');
```

It's a bit silly. A `default` export is doable too, but as an external TypeScript user, I find it inconvenient to have a separate import syntax and/or group for importing this one function verses any associated types the type definitions also export.

**Comment by k2snowman69** [comment]
I ran into something like this recently, have you tried typescript's `esModuleInterop` requirement that was introduced in 2.7?

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop

With this turned on in my code base my code looks like this:
```
import cosmiconfig from "cosmiconfig";

const explorer = cosmiconfig("sortier");
...

**Comment by davidtheclark** [comment]
Thanks for the suggestion, but I'm not interested right now in supporting specific TypeScript usage patterns, when alternatives already work ok.

**Comment by JoshuaKGoldberg** [comment]
@davidtheclark although this is mostly relevant to TypeScript users right now, this is going to become an issue for regular JavaScript folks when Node starts supporting ES modules and folks use them natively. TypeScript is just emulating the new spec. Does that help sway your opinion?

_(in retrospect, I should have phrased this issue as a native JS one)_

Does that help? No worries if not 😄

**Comment by davidtheclark** [comment]
You're right, @JoshuaKGoldberg, that this is ES module syntax; but the aversion to a default export seems specific to TypeScript? I think a default export is fine and standard, so I'm not sure why it would become an issue for people using ES modules. I'd rather not make API changes to accommodate preferences like this, as long as the current API does work fine.

**Comment by JoshuaKGoldberg** [comment]
Fair, agreed. In that case, would you take in a PR that adds a default export to the package?

The `esModuleInterop` solution works in limited cases but can subtly break code _(it's a behavior change)_.

**Comment by k2snowman69** [comment]
Not to be a stickler but Typescript (from their documentation) highly recommends that you move over to using the esModuleInterop solution... From their documentation:
```
Note: The new behavior is added under a flag to avoid unwarranted breaks to existing code bases. We highly recommend applying it both to new and existing projects. For existing projects, namespace imports (import * as express from "express"; express();) will need to be converted to default imports (import express from "express"; express();)
```

The reason for this is the old `import * as ` syntax does go against the tc39 spec and will not be supported long term.

I don't disagree that this won't make typescript user's lives easier in the short term but if added, in the long term you'll likely just end up deleting it anyways.

I'd say the better solution for your project is to upgrade to using the esModuleInterop (I just did this across my codebases, its a simple search and replace of `import * as` with `import`).

Adding and removing it doesn't impact me at all, more just wanted to let you know that long term the `import * as ` syntax will likely be deprecated and removed in future versions of typescript.
