### ISSUE TITLE
Importing a shared config

### ISSUE THREAD

**Issue by k2snowman69** [davidtheclark/cosmiconfig#162]
### Overview
I've been looking into having a package of shared configs and then utilizing those shared configs in each of my projects. Somewhat an extension on https://github.com/davidtheclark/cosmiconfig/issues/110 but hopefully requires no feature changes on cosmiconfig. I've gotten pretty far, the last issue is actually loading the shared config.

### Background
I've published a new package `https://www.npmjs.com/package/@snowcoders/renovate-config` (note I haven't actually committed the code to github yet, this is a prototype scenario) which exports several configs:
```
import { husky, lintStaged, prettier, sortier } from "@snowcoders/renovate-config";
```
To use an example, the `prettier` config looks like:
```
export const prettier = {
  printWidth: 100
};
```

The goal was to be able to have `@snowcoders/renovate-config` as a dependency of my projects and then simply require import the shared config into the base configuration of that project. So in the base of all my projects I would have:
```
/// .prettierrc.js
var configs = require("@snowcoders/renovate-config");

module.exports = configs.prettier;
```

I liked this because as noted in #110 there can be multiple ways to extend and change the config, therefore it's out of the scope of cosmiconfig to allow extending. However, since this is JS, I can now in code change the config as I want.

### The issue
Annoyingly when I run prettier from the project with the `.prettierrc.js` I get an error:
```
D:\Projects\exec-if-exists>npm run prettier

> exec-if-exists@1.0.0 prettier D:\Projects\exec-if-exists
> prettier "./src/index.ts"

[error] Invalid configuration file: Cannot find module '@snowcoders/renovate-config'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! exec-if-exists@1.0.0 prettier: `prettier "./src/index.ts"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the exec-if-exists@1.0.0 prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RickyPatel\AppData\Roaming\npm-cache\_logs\2018-12-16T23_22_43_499Z-debug.log
```

Now I can understand if cosmiconfig doesn't load packages from node_modules but even if I attempt to change the require to pull in the relative path:
```
var configs = require("./node_modules/@snowcoders/renovate-config");

module.exports = configs.prettier;
```

I still seem to get the same error.

### Conclusion
I'm just trying to figure out why this module isn't able to be loaded. I would expect the relative path solution should have resolved properly but I'm unsure why not and I'm just looking for guidance to work around this issue.

**Comment by davidtheclark** [comment]
@k2snowman69 Yeah, this is a dark and thorny path to go down. Unless you can show that Comsiconfig is not doing something that it should be doing, I don't think this error signals a problem with Cosmiconfig: it's just trying to load configs from where Prettier is pointing it. There are any number of things within your module or Prettier that might end up causing this error.

Please reopen if you think you've found a problem with Cosmiconfig.

**Comment by k2snowman69** [comment]
@davidtheclark I think I can scope the problem down... though it will have to be through an example repository, hope that's okay!

```
git clone https://github.com/k2snowman69/cosmiconfig-npm-config/
cd cosmiconfig-npm-config
npm install
npm run start
```

This contains a slimmed down version of the problem stated above with the only dependencies being `@snowcoders/renovate-config` (which contains the shared config) and `cosmiconfig`.

The index.js is something like this:
```
const cosmiconfig = require("cosmiconfig");

const explorer = cosmiconfig("prettier");
const result = explorer.searchSync();

if (result == null) {
  console.log("Failed to get config");
} else {
  console.log("Found config:");
  console.log(JSON.stringify(result));
}
```

I've set it up so that when you run `npm run start` it runs cosmiconfig and attempts to load the prettier config.
```
D:\Temporary\cosmiconfig-example>npm run start

> cosmiconfig-example@1.0.0 start D:\Temporary\cosmiconfig-example
> node index.js

module.js:550
    throw err;
    ^

Error: Cannot find module '@snowcoders/renovate-config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Temporary\cosmiconfig-example\.prettierrc.js:2:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Expected is actually something like this:
```
Found config:
{"config":{},"filepath":"D:\\Temporary\\cosmiconfig-example\\.prettierrc.js"}
```
