### ISSUE TITLE
Nested packageProp path

### ISSUE THREAD

**Issue by iamogbz** [davidtheclark/cosmiconfig#164]
Using `cosmiconfig` in a yarn version tool, [`yvm`](https://github.com/tophat/yvm). It would be helpful to be able to use the yarn version in the package.json engines prop as a search place for configuration. e.g.
```json
packageProp: 'engines.yarn',
```
A custom loader would probably work, but it seemed like a useful native feature regardless.

**Comment by iamogbz** [comment]
Noticed it was briefly mentioned in https://github.com/davidtheclark/cosmiconfig/issues/126#issuecomment-384268068, still think it's worth revisiting.

**Comment by iamogbz** [comment]
@olsonpm so I attempted using a custom loader to solve this, but once it detects the `package.json` filename it short circuits to using the `loadPackageProp`
https://github.com/davidtheclark/cosmiconfig/blob/85d60b55a6f0176c6fadb93e9b2670c73c667674/src/createExplorer.js#L181-L184
An option would be allowing the `package.json` to have a specific custom loader. However I think the nested `packageProp` option would be better, as it only requires updating the following line
https://github.com/davidtheclark/cosmiconfig/blob/85d60b55a6f0176c6fadb93e9b2670c73c667674/src/createExplorer.js#L176
With this; or something similar (`lodash` is already included in the `yarn.lock`)
```js
const packagePropValue = lodash.get(parsedContent, this.config.packageProp); 
```

**Comment by olsonpm** [comment]
hmm, that short circuit smells like a misdesign on our part as it prevents anyone from using package.json as a configuration file.  I'll need to think on that.

**Comment by davidtheclark** [comment]
Yeah, I think this is something we should support, @iamogbz. Since this is the first request related to a custom `package.json` loader, I think I'm in favor of supporting dot notation (as @iamogbz suggests) instead of allowing people to specify custom `package.json` loaders — which seems like a more significant change, and I'm having a hard time thinking of what people might do *other than* the equivalent of dot notation.

**Comment by iamogbz** [comment]
@davidtheclark I can put up a PR with this change, already have most of the code running locally.
