### ISSUE TITLE
Add support for Function Configuration

### ISSUE THREAD

**Issue by myuseringithub** [davidtheclark/cosmiconfig#165]
Wondering if configuration could be loaded as a function passing it some arguments. The same way Babel v7 `Config Function API`  loads a configuration function passing it an API object. [babeljs.io/docs/en/config-files#config-function-api](https://babeljs.io/docs/en/config-files#config-function-api)

**Comment by olsonpm** [comment]
I haven't used cosmiconfig in a while, but what you're asking about should work.  Cosmiconfig is more concerned with finding and parsing your config file rather than what you do with it.

**Comment by myuseringithub** [comment]
Why don't tools like `Yarn` and `Babel` use shared modules for configuration lookup and loading like `Cosmiconfig` ?

**Comment by olsonpm** [comment]
> Maybe then should add support for "parsing" a configuration as a function, seems to be a more powerful pattern for config files.

cosmiconfig parses js files, so it can parse functions.  If you provide a sample repo with code that doesn't work like you expect then I can understand your problem better.

<br>

> Why don't tools like Yarn and Babel use shared modules for configuration lookup and loading like Cosmiconfig ?

Only the library authors can tell you that :)

**Comment by chrisblossom** [comment]
I made [ex-config](https://github.com/chrisblossom/ex-config) to handle the parsing of config files. @myuseringithub maybe it will work for your use-case.

**Comment by myuseringithub** [comment]
@chrisblossom By the way, loading configuration file shouldn't be mixed with the lookup algorithm, I think its better to be split into a separate module. `Cosmiconfig` is limited in its design, it loads the files even when required and stops on the first configuration found. Now I understand why its not used in popular projects.

**Comment by davidtheclark** [comment]
> Cosmiconfig is limited in its design, it loads the files even when required and stops on the first configuration found. Now I understand why its not used in popular projects.

@myuseringithub This sounds like criticism but I don't think I understand the problem. It's established above that you can do what you want with Cosmiconfig, right? Configuration can be a `.js` file exporting a function.

You wish this was two modules instead of one? If you want to use separate packages for looking up configuration files and loading them, those packages exist.

**Comment by myuseringithub** [comment]
I wrote it after trying to integrate it to my module, then realizing I'm just better off separating the logic of the lookup and loading of the config file. The module doesn't serve my needs for the lack of customizations I need. 
Take it as a constructive comment.
> If you want to use separate packages for looking up configuration files and loading them, those packages exist.
That's true, maybe these are better integrated in a wrapper module like `Cosmiconfig`.

**Comment by sudo-suhas** [comment]
@davidtheclark Do you think we should add a section listing the packages that _do_ use `cosmiconfig`? Perhaps that can give a good idea of what `cosmiconfig` can do based on user's experience with the relatively more popular user facing utilities like `prettier` and `stylelint`. Although I don't mean to offend @myuseringithub, this interaction gives me the impression that he either did not read the documentation thoroughly or it wasn't clear enough when he did try to do so. Sometimes examples can be a good way to understand.
