### ISSUE TITLE
Config loading always relative to the path, not accounting for hoisted dependencies

### ISSUE THREAD

**Issue by Andarist** [davidtheclark/cosmiconfig#166]
So from what I understand this is how the config should be loaded:
https://github.com/michael-ciniawsky/postcss-load-config/blob/4349ea939d42d6ac4a4c1d3e3b231d3588431a14/src/index.js#L52

It doesn't work if the `path` is outside of the cwd, which happens for monorepos with hoisted dependencies.

Example tree
```js
.
├── node_modules
│   └── dependency
│       └── dist
│           └── foo.min.css
├── package.json
└── packages
    └── bar
        ├── src
        │   └── main.js
        └── postcss.config.js
```
Where `main.js` requests `dependency/dist/foo.min.css` - and the postcss config IMHO still should be resolved to `./packages/bar/postcss.config.js`, because its where the app lives.

**Comment by olsonpm** [comment]
There are a couple things to note:

- which version are you asking about?  `postcss-load-config` uses v4, but is this what you are using?
- in v5, [this part of the documentation](https://github.com/davidtheclark/cosmiconfig#explorersearch) should help

e.g.

```js
// main.js
const cosmiconfig = require('cosmiconfig')

result = cosmiconfig('postcss').searchSync(__dirname)

console.log(result.filepath)
```

**Comment by Andarist** [comment]
Thanks for the reply!

I've come at this problem with `postcss-load-config`. Haven't noticed that it was using outdated dependency - my bad, sorry.

Seems like `search` is the way to go, thanks for the tip. I'll suggest this to the `postcss-load-config` maintainers.
