### ISSUE TITLE
custom search places doesn't find a file but loadSync does?

### ISSUE THREAD

**Issue by kelly-tock** [davidtheclark/cosmiconfig#167]
I have some code that looks up config, and am coming up empty as to why it's not finding the example file i'm testing with. 

```js
const path = require('path');
const fs = require('fs');
const dotenv = require('dotenv');
const cosmiconfig = require('cosmiconfig');
const _isEmpty = require('lodash/isEmpty');


module.exports = function(envFileName) {

  const prefix = '.env';

  let localSearchPlaces = [
    `${prefix}.local`,
    `webpack/${prefix}.local`
  ];

  if (envFileName) {
    localSearchPlaces = [`${envFileName}.local`];
  }

  const dotEnvLoader = (filepath, content) => {
    const result = dotenv.parse(content);
    return result ? result : null;
  };

  const loaders = {
    '.local': dotEnvLoader,
    noExt: dotEnvLoader
  };

  const localExplorer = cosmiconfig('localEnv', { localSearchPlaces, loaders });
  const localSearchedFor = localExplorer.searchSync(); // this is empty

  let loadResult = {};
  if (envFileName) {
    if (fs.existsSync(path.resolve(process.cwd(), `${envFileName}.local`))) {
      loadResult = localExplorer.loadSync(path.resolve(process.cwd(), `${envFileName}.local`));
    }
  } else {
    if (fs.existsSync(path.resolve(process.cwd(), `webpack/${prefix}.local`))) {
      loadResult = localExplorer.loadSync(path.resolve(process.cwd(), `webpack/${prefix}.local`));
    }

    if (fs.existsSync(path.resolve(process.cwd(), `${prefix}.local`))) {
      loadResult = localExplorer.loadSync(path.resolve(process.cwd(), `${prefix}.local`));
    }
  }

// depending on where I put the `.env.local` file, both loads work. 

  let localSearchForAppEnv = {};
  if (localSearchedFor && !localSearchedFor.isEmpty) {
    localSearchForAppEnv = localSearchedFor.config;
  }
  if(loadResult && !loadResult.isEmpty) {
    localSearchForAppEnv = {
      ...localSearchForAppEnv,
      ...loadResult.config
    };
  }

 // ...other stuff
}

```

I am running this from a script in my project, and i've placed a `.env.local` file under a webpack directory. the searched for can't find it, but loading it works. 

I removed some other code in this same file that is the same pattern, but looks for `.env` and its searching for it and finds it perfectly. 

any ideas?

**Comment by olsonpm** [comment]
Would you mind setting up a sample repo with the failing code?

**Comment by kelly-tock** [comment]
https://github.com/kellyrmilligan/cosmiconfig-repro

just run `./node example.js`

that is my other account.

**Comment by kelly-tock** [comment]
the console will log out the results.

**Comment by olsonpm** [comment]
Thanks much - I'll take a look when I have time.

**Comment by olsonpm** [comment]
rename `localSearchPlaces` to `searchPlaces` and it works.

About us not validating options, that's another matter.  It's common for js libraries to only pull the stuff they care about and not worry about extras so how the code is currently written is pretty standard.  I do wonder if we exposed an option "strict", how many people would actually use it.  Assuming "strict: true" would tell cosmiconfig to strictly validate the options object

**Comment by kelly-tock** [comment]
Oh man I was going blind I guess with the shorthand syntax. Ugh 😑 sorry about that. As you can see i tried several ways and just didn’t see it.

**Comment by olsonpm** [comment]
No problem at all.  Those bugs are the most frustrating ha
