### ISSUE TITLE
Support scoped packages?

### ISSUE THREAD

**Issue by jochakovsky** [davidtheclark/cosmiconfig#168]
cosmiconfig requires a `moduleName`: https://github.com/davidtheclark/cosmiconfig#modulename

Some NPM packages are scoped, so the name field of package.json will be in the format `@foo/bar`. The latest version of cosmiconfig doesn't seem to support using the actual name of a scoped package as the moduleName. Here's what happened when I tried:
- Adding a `"@foo/bar"` config section to package.json worked successfully
- Can't add a `.@foo/barrc` file, since slashes are not allowed in filenames. Creating a folder `.@foo` with a `barrc` file inside doesn't seem to be picked up by cosmiconfig

Typescript had a similar issue with scoped packages, since type definitions for package `foo` were published under `@types/foo`. If the package being typed is scoped, there was no valid way to publish a type definition package for it (`@types/@foo/bar` is invalid, both because it has two @ signs and because it has two slashes), so they translate `@foo/bar` to `foo__bar`, publishing the types under `@types/foo__bar` in this example. Cosmiconfig could follow Typescript's example here - if the `moduleName` is scoped, it could search for package.json's `"foo__bar"`, `.foo__barrc`, `.foo__barrc.json`, etc..

Alternatively, since cosmiconfig doesn't actually check that `moduleName` matches package.json's name field exactly, cosmiconfig could make no code changes and just add some documentation in README.md about the limitations of `moduleName` and suggest a standard way of converting scoped module names to cosmiconfig-compatible module names.

**Comment by olsonpm** [comment]
Personally this seems to only be a problem in theory as I can't imagine anyone expecting `.@foo/bar.json` to work in practice.  The internet is large though and a succinct blurb of documentation sounds painless, so I guess I could go either way.

**Comment by jochakovsky** [comment]
Sounds good to me! Do you think the documentation should suggest some convention or just mention that `moduleName` should only contain characters that are allowed in a file name?

**Comment by olsonpm** [comment]
Sounds reasonable to me.

**Comment by olsonpm** [comment]
Sorry - I meant I liked

> moduleName should only contain characters that are allowed in a file name.

**Comment by davidtheclark** [comment]
I agree that documentation about this makes sense 👍
