### ISSUE TITLE
Fails to load config with . period in path

### ISSUE THREAD

**Issue by dead** [davidtheclark/cosmiconfig#170]
I'm having a problem with [apollo-tooling](https://github.com/apollographql/apollo-tooling) and seems an [issue from cosmiconfig](https://github.com/apollographql/apollo-tooling/issues/838#issuecomment-450526193) 

https://github.com/davidtheclark/cosmiconfig/blob/85d60b55a6f0176c6fadb93e9b2670c73c667674/src/createExplorer.js#L61 
In this line, when `place` have a folder with a dot in the last folder of a path, `example path: /some/stuff/foo.bar` (foo.bar is a directory). It throws the `No loader specified for` error.

Replacing the original `config.searchPlaces.forEach` with: 

```js
    config.searchPlaces.forEach(place => {
      const isDirExists = fs.existsSync(place) && fs.lstatSync(place).isDirectory()
      if (!isDirExists) {
        const loaderKey = path.extname(place) || 'noExt';
        const loader = config.loaders[loaderKey];
        if (!loader) {
          throw new Error(
            `No loader specified for ${getExtensionDescription(
              place
            )}, so searchPlaces item "${place}" is invalid`
          );
        }
      }
    });
```

Fixed my issue in apollo-tooling.

**Comment by davidtheclark** [comment]
Hi @dead. I think I understand the problem you're having, but not quite sure. 

An item in `searchPlaces` needs to be a relative path to a file (it will be interpreted relative to each directory that is searched). It cannot be a directory — whether the directory includes a period or not.

It would help if you can create a test case that fails, to illustrate your problem.

**Comment by dead** [comment]
@davidtheclark 
Thanks for replying 😄
And you are right. apollo-tooling was passing a directory in the searchPlaces.

https://github.com/apollographql/apollo-tooling/commit/4099326a83f2e9ad79f89460d08ded2adaa63c82#diff-9561bb654547e5c1d48883bb33a95053L280
But it seems they fixed this 3 days ago.
