### ISSUE TITLE
Support for rc files with extensions

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#18]
I read about the latest ESLint release (http://eslint.org/blog/2015/11/eslint-v1.10.0-released/) and thought that what they're doing with rc file extensions would be worth mimicking.

The idea is that rc files would not have to be extensionless: if user adds an extension to the file (e.g. `.stylelintrc.yaml`), then they'll get syntax highlighting in their editor and more exact error stacks if there are syntax errors.

**Comment by TrySound** [comment]
@davidtheclark Maybe make it optional to reduce fs access?

**Comment by davidtheclark** [comment]
Yep, I was thinking about that problem too.

**Comment by MoOx** [comment]
Sounds good

**Comment by TrySound** [comment]
Or at least check .stylelintrc without extension first, caz it more usual.

**Comment by davidtheclark** [comment]
Unless someone beats me to it, I will work on this after I get back from vacation in a week and a half.
