### ISSUE TITLE
Consider upgrading `require-resolve` to `require`

### ISSUE THREAD

**Issue by grabbou** [davidtheclark/cosmiconfig#182]
According to this issue: https://github.com/sindresorhus/resolve-from/issues/8, `require.resolve` accepts custom paths as of Node 8.

Opening this issue as I've run into mocking troubles while using Jest and MemoryFS. I am not sure what's the compatibility of Cosmiconfig against Node versions, but I would be happy to submit a PR to use that if it sounds like a good idea.

**Comment by olsonpm** [comment]
Compatibility is >= node 4 atm.  Honestly I'm not understanding the use-case for your proposed PR, but the require.resolve functionality sounds interesting.  Hadn't heard of it.

**Comment by davidtheclark** [comment]
@grabbou We're not sure we understand the problem or suggested solution. Please re-open if you want to follow up with more of those details.
