### ISSUE TITLE
Doesn't it parse ini format?

### ISSUE THREAD

**Issue by panlina** [davidtheclark/cosmiconfig#199]
I mean the traditional ini format, like:
```
a=b
c=d
```
It gives the plain string, instead of the parsed object, like `{a: "b", c: "d"}`.

**Comment by olsonpm** [comment]
Unfortunately the 'ini' format isn't supported out of the box by cosmiconfig.  Instead we support `js`, `json`, and `yaml`.

>By default, Cosmiconfig will start where you tell it to start and search up the directory tree for the following:
>
>    a package.json property
>    a JSON or YAML, extensionless "rc file"
>    an "rc file" with the extensions .json, .yaml, .yml, or .js.
>    a .config.js CommonJS module

To support the 'ini' format you will need a [loader](https://github.com/davidtheclark/cosmiconfig#loaders) to handle it.  It's possible someone has already written one, but I don't know of any (didn't find one off a quick search).

**Comment by panlina** [comment]
OK. Thanks for the info.

**Comment by sveyret** [comment]
Maybe [confinode](https://www.npmjs.com/package/confinode) would fit your needs…

**Comment by d-fischer** [comment]
The .ini format is too niche to put into the default loaders. Therefore, I'm closing this.
