### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by corysimmons** [davidtheclark/cosmiconfig#200]
Working on a React component lib with the following folder structure:

<img src="https://user-images.githubusercontent.com/224636/60197361-11ebef00-97f4-11e9-9184-26bf979a8f77.png" width="200px">

`example` is a bare bones CRA app that is using a `yarn link`'d version of the component I'm trying to release a lib for.

Copied code from README:

![image](https://user-images.githubusercontent.com/224636/60197541-6d1de180-97f4-11e9-9864-9d50125ad2e8.png)

`yarn dev` 👇Terminal

```
Compiled with warnings.

../node_modules/import-fresh/index.js
Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

I Googled the error and landed here: https://github.com/webpack/webpack/issues/196

Then tried to add/use `@babel/plugin-syntax-dynamic-import` to no avail.

I should mention the package itself is scoped to an org, but I get the same error if I try it and it isn't scoped to an org... I suspect it has something to do with `yarn link`?

**Comment by chrisblossom** [comment]
Are you trying to use `cosmiconfig` in the browser? I suspect [liady/webpack-node-externals](https://github.com/liady/webpack-node-externals) might solve your problem.

**Comment by corysimmons** [comment]
Something like that is probably my problem. I'm trying to make a React component lib where people can go `npm i foo`, `import foo from 'foo'`, create a `foo.config.js` at root of their React app, and the component is able to reference that config file.

Perhaps I should make some sort of provider component to pass config into... 🤔 

Sorry, new to this. Thanks for the quick response.
