### ISSUE TITLE
User defined searchPlaces/cwd setting

### ISSUE THREAD

**Issue by manuelbieh** [davidtheclark/cosmiconfig#203]
Hey,

I'm currently trying to get rid of all the unnecessary noise in my projects. And by noise I basically mean files or folders in the top level directory of a project that are not `src`, `dist`, `lib`, `build`, `node_modules` or `package.json`.

Unfortunately that's not so easy because many of the common tools (eslint, babel, prettier, …) are all looking for config files in a project's _root_ folder (or its parents) using cosmiconfig.

I would love to have a way to just hide all my config files in a subfolder like `.config` inside of my project directory or maybe even in its own `node_modules/@mycompany/configs/presets/react-app` dependency.

So my idea/question is: would it be possible/realistic to add a lookup feature to cosmiconfig so that I can define a custom path in my `package.json` to tell cosmiconfig where to start looking for config files and then traverse its way up from _there_ instead of from `process.cwd()`?

Example:
package.json
```json
{
  "name": "my-project",
  "cosmiconfigRoot": "./config",
  ...
}
```

When cosmiconfig is then used to search for config files it would first look for a `package.json`, checks it for a `cosmiconfigRoot` property (or `cosmiconficCwd`, `cosmiconfigSearchFrom` or whatever you think is a good name) and then start looking for `` `${cosmiconfigRoot}/.${moduleName}rc` ``.

Or to put it in other words: I'm looking for a way to configure the `searchFrom` option as a **consumer** of a tool, _not_ as the **author**. Would that be possible? *Is* that even possible already and I just haven't seen it in the docs? Do you have any concerns why this is might not be a good idea? Can I help you somehow to implement such a feature?

**Comment by davidtheclark** [comment]
Hi @manuelbieh. There's some discussion of this kind of thing in the issue history. Authors of packages that use cosmiconfig get to make the decision how to configure `searchPlaces`, not end users: the way that a package's configuration gets loaded is part of that package's API, not something cosmiconfig controls — even if it uses cosmiconfig as a helper behind the scenes. I suggest making this feature request to the package that you're directly using.
