### ISSUE TITLE
Remove yarn.lock

### ISSUE THREAD

**Issue by chrisblossom** [davidtheclark/cosmiconfig#206]
I would like to drop `yarn.lock` from this repo. Lock files are not a good fit for libraries because they are ignored by the end user consuming the library.

Basically our tests can pass, but will be broken for users. (which also why it is a good idea to _"[Reinstalls dependencies to ensure your project works with the latest dependency tree](https://github.com/sindresorhus/np#why)"_ on publish.)

This is especially true for yarn because yarn requires all people developing the software to use the same version of yarn, which is not currently enforced in this library. The `yarn.lock` format can (and has) changed between minor yarn updates.

I've also noticed that the newer versions of yarn defaults to exact versions, so we now have [a mix of exact and ^ inside package.json](https://github.com/davidtheclark/cosmiconfig/blob/47d8951caf1ed5730e948d0aa0c65309eb53208f/package.json#L108-L142) which should be fixed.

https://www.twilio.com/blog/lockfiles-nodejs

**Comment by davidtheclark** [comment]
This was done in #216.
