### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by nikolay-borzov** [davidtheclark/cosmiconfig#213]
`const { cosmiconfig } = require('cosmiconfig');`
should be
`const cosmiconfig = require('cosmiconfig');`

**Comment by davidtheclark** [comment]
Yes, sorry @nikolay-borzov we're in a transition period and the README on master reflects the upcoming, not-yet-released version. You can see the README of the latest release at https://github.com/davidtheclark/cosmiconfig/tree/5.2.1
