### ISSUE TITLE
5.2 - 6.0

### ISSUE THREAD

**Issue by J-Tech-Foundation** [davidtheclark/cosmiconfig#220]
uh, when i updated the package... the cosmiconfig function stopped working

**Comment by davidtheclark** [comment]
@J-Tech-Foundation Yep, a major version bump means there are breaking changes. Please read the changelog and the docs and file a more specific issue if those instructions don't work.

**Comment by J-Tech-Foundation** [comment]
i am experiencing this same issue, but this time as i was writing a package for discord.js, can you specify what all the changes were in the update so i can improvise work arounds?
