### ISSUE TITLE
Inconvenient types import / export

### ISSUE THREAD

**Issue by ffflorian** [davidtheclark/cosmiconfig#221]
First and foremost: Great that you switched from Flow to TypeScript! Although, when switching from `@types/cosmiconfig` to the types which are now provided by this package, I experienced the following issues:

---

### No direct import for `CosmiconfigResult`

Currently when I want to declare a variable which will get the result from `cosmiconfig.search()`, I need to do it like this:

```ts
import {cosmiconfig} from 'cosmiconfig';
import {CosmiconfigResult} from 'cosmiconfig/dist/types';

let result: CosmiconfigResult;
```

But I'd like to import it conveniently like this:

```ts
import {cosmiconfig, CosmiconfigResult} from 'cosmiconfig';

let result: CosmiconfigResult;
```

Unfortunately this is not possible since `CosmiconfigResult` is not re-exported from the `types` dir. I tried fixing it but since `isolatedModules: true` is set in `tsconfig.json`, re-exporting is disallowed:
```
src/index.ts:137:56 - error TS1205: Cannot re-export a type when the '--isolatedModules' flag is provided.

137 export { cosmiconfig, cosmiconfigSync, defaultLoaders, CosmiconfigResult };
```

---

### No clear return type of `cosmiconfig()`

I have a class which adds cosmiconfig as a property and I have to define its type. Since `cosmiconfig()` returns an object (and is [especially excluded from needing a convenient return type](https://github.com/davidtheclark/cosmiconfig/blob/b185782355ac1f5906b6d2c9cfd68b83df249c31/src/index.ts#L46)), I need to declare it like this:

```ts
import {cosmiconfig} from 'cosmiconfig';

class MyClass {
  private readonly cosmiconfig: ReturnType<typeof cosmiconfig>;

  constructor() {
    this.cosmiconfig = cosmiconfig('myconfig');
  }
}
```

I'd rather like to be able to declare it like this:

```ts
import {cosmiconfig, Cosmiconfig} from 'cosmiconfig';

class MyClass {
  private readonly cosmiconfig: Cosmiconfig;

  constructor() {
    this.cosmiconfig = cosmiconfig('myconfig');
  }
}
```

Where `Cosmiconfig` is an interface which describes the return value of `cosmiconfig()`.

**Comment by chrisblossom** [comment]
Using Typescript's `ReturnType` is the correct solution here.

```ts
import { cosmiconfig, cosmiconfigSync } from 'cosmiconfig';

type Explorer = ReturnType<typeof cosmiconfig>
const explorer: Explorer = cosmiconfig('example');
type SearchResult = ReturnType<typeof explorer.search>;
type LoadResult = ReturnType<typeof explorer.load>;

type ExplorerSync = ReturnType<typeof cosmiconfigSync>
const explorerSync: ExplorerSync = cosmiconfigSync('example');
type SearchSyncResult = ReturnType<typeof explorerSync.search>;
type LoadSyncResult = ReturnType<typeof explorerSync.load>;
```

I would not recommend directly importing from `cosmiconfig/dist/types` (or any other `dist/*` file) because they are not protected by semver.

**Comment by ffflorian** [comment]
@chrisblossom I see. And would you accept a PR which would export those types directly? Or would you advise everyone to create them on their own?

**Comment by chrisblossom** [comment]
> would you accept a PR which exports those types directly?

This is up to @davidtheclark. I personally think using `ReturnType` is the preferred way for a consumer of a library to get a the return type of a function. This lets consumers not care about implementation details / less potential breaks to semver. Unless there is a use case where this is not possible, my vote is to not export it directly.


> (and is [especially excluded from needing a convenient return type](https://github.com/davidtheclark/cosmiconfig/blob/b185782355ac1f5906b6d2c9cfd68b83df249c31/src/index.ts#L46))

Typescript infers the return type [from here](https://github.com/davidtheclark/cosmiconfig/blob/b185782355ac1f5906b6d2c9cfd68b83df249c31/src/index.ts#L55-L61) and would not be exported if it was explicitly typed. [`@typescript-eslint/explicit-function-return-type`](https://github.com/typescript-eslint/typescript-eslint/blob/736a074b80eafd88376a90e6595a42217d939890/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) is a great lint rule to ensure your function always returns the correct value, but IMO is excessive here and is better inferred via Typescript's [`as const`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)

**Comment by ffflorian** [comment]
> I personally think using `ReturnType` is the preferred way for a consumer of a library to get a the return type of a function

I disagree. `ReturnType` is a [Utility Type](https://www.typescriptlang.org/docs/handbook/utility-types.html) which IMO is a good fallback if you don't have any interface to on hand. The preferred way should be a clear interface. But that's just my opinion. :slightly_smiling_face:

**Comment by davidtheclark** [comment]
I will leave things as they are unless there's a stronger argument that avoiding `ReturnType` is both (a) the widely preferred solution, and (b) the better one. I definitely see the *advantages* of `ReturnType`, and don't think counterbalancing disadvantages have been explained. I don't have any opinion of my own here.

**Comment by davidtheclark** [comment]
Closing as stale.
