### ISSUE TITLE
How to configure webpack to fix "Can't resolve 'module' from resolve-from"

### ISSUE THREAD

**Issue by denvash** [davidtheclark/cosmiconfig#222]
I'm having a hard time to run `babel-plugin-macros` with a storybook,
it seems I need to configure the webpack:

I asked the same question on all related repositories, the build-time error I getting is:

```
ERROR in ./node_modules/cosmiconfig/node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in '/home/denvash/dev/github/gissy/dashboard/node_modules/cosmiconfig/node_modules/resolve-from'
 @ ./node_modules/cosmiconfig/node_modules/resolve-from/index.js 3:15-32
 @ ./node_modules/cosmiconfig/node_modules/import-fresh/index.js
 @ ./node_modules/cosmiconfig/dist/loaders.js
 @ ./node_modules/cosmiconfig/dist/index.js
 @ ./node_modules/babel-plugin-macros/dist/index.js
 @ ./node_modules/tailwind.macro/macro.js
 @ ./src/styles/index.js
 @ ./src/styles/Button/Button.stories.jsx
 @ ./src sync \.stories\.jsx$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

Exploring the error code lead to:

```
// @ node_modules/cosmiconfig/node_modules/resolve-from
const path = require('path');
const Module = require('module');

...
```

Requiring `module` exports `NodeJs.Module`

```
declare module "module" {
    export = NodeJS.Module;
}
```

So I guess I need to add additional configuration to webpack to solve it.

Any help will be much appreciated :)

**Comment by davidtheclark** [comment]
Hm, this doesn't seem like an issue with cosmiconfig.

This library is not intended to be run in the browser. Is there some other reason you're trying to compile it with Webpack?

**Comment by Thibaut-Fontaine** [comment]
To solve this issue you have to install the `babel-plugin-macros`: 
```
yarn add babel-plugin-macros --dev
```
Then add a `.babelrc` file to your root directory:
```json
{
  "plugins": ["macros"]
}
```

That should work

(original answer : https://github.com/storybookjs/storybook/issues/7033#issuecomment-510885558)

**Comment by jamachad** [comment]
Solution for me was on to add the following on webpack.config 

node: {
        module: "empty"
     }

**Comment by 0xYao** [comment]
> To solve this issue you have to install the `babel-plugin-macros`:
> 
> ```
> yarn add babel-plugin-macros --dev
> ```
> 
> Then add a `.babelrc` file to your root directory:
> 
> ```json
> {
>   "plugins": ["macros"]
> }
> ```
> 
> That should work
> 
> (original answer : [storybookjs/storybook#7033 (comment)](https://github.com/storybookjs/storybook/issues/7033#issuecomment-510885558))

Got this error

```
 Error  Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.plugins[0] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function.
   Details:
    * configuration.plugins[0] should be an object:
      object { apply, … }
      -> Plugin instance.
    * configuration.plugins[0] should be an instance of function.
      -> Function acting as plugin.
```

My webpack version is `^5.88.2`
