### ISSUE TITLE
npm link reads from shared folder

### ISSUE THREAD

**Issue by wtrocki** [davidtheclark/cosmiconfig#223]
When using npm link to project cosmicconfig is going to look up the path of the original package and not symlinked one. I'm not sure if this problem is solvable by the library but any workaround will be appreciated.

TL;DR if we npm link package config will not be read.

**Comment by davidtheclark** [comment]
I think that this is likely a problem for your package, not for cosmiconfig. Cosmiconfig uses the paths that you provide; it doesn't make assumptions based on its own location in the file system. You may need to adjust the paths that you provide to cosmiconfig.

However, if you think that you're passing cosmiconfig paths that *should* work but are not, then that would indicate a bug.
