### ISSUE TITLE
Expose api access to final config 

### ISSUE THREAD

**Issue by desfero** [davidtheclark/cosmiconfig#227]
It would be good to have access to the final config or just to default `searchPlaces`.

https://github.com/davidtheclark/cosmiconfig/blob/d26b10550df566648c5a9a05d893d800c9b129c6/src/index.ts#L106-L112

My use case requires allowing multiple configs per project (root config and sub configs per directory). To achieve that I'm just using glob matching, for .e.g (**/.libname.rc). Given the above, would be good to have access to generated `searchPlaces`. 
The easiest way would be to just expose `config` from `ExplorerBase`: https://github.com/davidtheclark/cosmiconfig/blob/master/src/ExplorerBase.ts#L16
by providing `getConfig` public method.

If that sounds okay let me know I can prepare a PR. Thanks 🤓

**Comment by davidtheclark** [comment]
I don't think I fully understand what you want to do with the default `searchPlaces`. Could you explain a little more?

**Comment by desfero** [comment]
As for now, `cosmiconfig` allows only to have a single config but for my use case, I just want to allow overwriting config in subdirectories. At the moment supported search places are just hardcoded in the code (check `CONFIG_PATTERNS`) here https://github.com/desfero/structlint/blob/6af837ab6b7a2ca6a34200aeb70be07d0d92a24a/src/config.ts#L52-L54
And that approach won't scale properly when `cosmiconfig` will start supporting a new file or name format. That's why would be good to have access to generated `searchPlaces` so then I can just  use it as:
```
return globby
    .sync(configExplorer.getSearchPlaces().map(place => `**/${place}`))
    .map(file => configExplorer.load(file))
```

**Comment by desfero** [comment]
@davidtheclark any thoughts?

**Comment by davidtheclark** [comment]
I'd rather not extend the API for this use case. The default search places are documented, and they should not change without a changelog note and documentation update — in which case you can update your code. 

If others feel a need for this feature, feel free to chime in.
