### ISSUE TITLE
Add support for <place your file type here>

### ISSUE THREAD

**Issue by sveyret** [davidtheclark/cosmiconfig#228]
I was about to create my own library for configuration file reading when I discovered _cosmiconfig_. What you've done is great, and almost meet what I wanted to do, except for a point: the need to create loaders to support a lot of useful file types. It seems important to me because, for example, someone writing code in _CoffeeScript_ or _TypeScript_ will want to be able to write its configuration file in the same language; someone writing all its configuration file in TOML will not want to write a configuration file in JSON. So you will probably always get a lot of feature request to add this and that file type to the library (there are currently 3 of them out of 10 total issues: #150, #199 and #224)!

Of course, you cannot support every single file type out of the box, because it would mean having lot and lot of dependencies which is not desirable.

But what I was thinking was more a way like _webpack_ is working. It is actually based on the [interpret](https://github.com/gulpjs/interpret) library which provides a dictionary of extensions and names of module used to load the corresponding file type. For each file extension, if one of the corresponding module can be required, then the file is read using this module. Otherwise, the file type is not supported.

The advantage is that _webpack_ currently support a lot of file types for its configuration, without having the needed dependencies itself. The final project needs to import one of the dependency if it wants to set its configuration in a specific file type, which is generally not a problem, because if, for example, you write your code in _TypeScript_, you already have the needed library as dependencies to read a _TypeScript_ configuration file.

Another advantage of adding such feature would be that tools using this library would not need to specify the supported file type, only the end-user would need to care to have the needed dependencies.

Would that be some thing you would be interested in (I could probably write a PR if you want) or do you think it is out of the scope of your project and I should fork it if I really want this behavior?

**Comment by davidtheclark** [comment]
I'm not inclined to do this for a few reasons:

- interpret is based on Node's `require.extensions` functionality, which is [deprecated](https://nodejs.org/api/modules.html#modules_require_extensions), so I don't want to rely on it.
- This sounds like a leaky abstraction that introduces confusing interfaces. (e.g. If I the end user install a random interpret-supported loader and it doesn't seem to work with your library, who is responsible? Me? The library? The loader module? Cosmiconfig?) cosmiconfig is not going to ask anything of the *end user*: it's providing library authors with a tool that end users should not need to know about.

I think that small custom loaders (and small npm packages if you want to share) is preferable.

**Comment by sveyret** [comment]
No problem, I'll do a fork then. Just a few remarks anyway:

* `require.extensions` is deprecated almost since the beginning of node but did not change and will most likely never change as it is used by every tool adding a managed file type (I don't know if `typescript` itself is using it, but at least `ts-node` is).
* I wouldn't like updating `require.extensions` in such library anyway because it is kind of “polluting” the node environment, especially if there are dozens of managed extensions. I was not really suggesting to use `interpret` but to create something similar.
* I completely agree that end user does not need to know about this library, this is just the tool author which would say how to set up configuration in its manual.
* This is how `webpack` is working, and it doesn't seem to be a problem to find responsibility in case of a bug.
* The inconveniences of small custom loaders is that:
  * Each tool author needs to import/implement the ones he wishes that end-user can use. If he wants to be exhaustive, he will have to constantly look for if a new loader has been released for a new file type and add it to its tool.
  * As each tool author may have different opinion on file type to support, there will be no consistency between tools. What I would like is to create a kind of standard way to load the configuration, so that end-users can use their favorite language each time they write a configuration file.
  * The custom loaders have all the needed dependencies (instead of just a module declaration), so if the tool author wants to be exhaustive, his tool will quickly be very heavy.

**Comment by sveyret** [comment]
FYI, I released [confinode](https://www.npmjs.com/package/confinode) to fit with my philosophical point of view.
