### ISSUE TITLE
Edit and save config

### ISSUE THREAD

**Issue by nikolay-borzov** [davidtheclark/cosmiconfig#236]
Config can be used to store values entered by the user so that on the next app run these values will be prefilled.

It would be great if `cosmiconfig` could save modified config:

```javascript
const { cosmiconfigSync, cosmiconfigSaveSync } = require('cosmiconfig')

const explorer = cosmiconfigSync('my-module')
const result = explorer.search(searchFrom)

// Do work ...

result.config.lastRun = new Date().getTime()

cosmiconfigSaveSync(result)
```

**Comment by ozum** [comment]
I had a similar need and created [edit-config](https://www.npmjs.com/package/edit-config) module for this purpose.

It can edit and save `cosmiconfig` files (JSON and YAML). You can also provide `cosmiconfig` options, which are passed directly to cosmiconfig.

Check it out:

```ts
import { DataFile, Manager, noLogger } from "edit-config";

const husky = await DataFile.load("husky", { cosmiconfig: true, logger: noLogger });

husky.set("hooks.pre-commit", "lint-staged");

if (husky.canSaved) await husky.save(); // Only JSON and YAML can be saved.
```

**Comment by davidtheclark** [comment]
Nice work, @ozum 👍  People who want this functionality can us edit-config.
