### ISSUE TITLE
Parsing and fixing JSON config files found

### ISSUE THREAD

**Issue by Berkmann18** [davidtheclark/cosmiconfig#237]
It's a great tool which I think misses the ability to fix JSON config files found so that packages that use `cosmiconfig` wouldn't necessarily have to handle JSON errors (especially when `explorer.search()` is used as it doesn't return the name of the config file found when there's an error).

I managed to implement `json-fixer` (_disclaimer: I made that so it could auto-fix invalid/erroneous JSON files in a similar context_) in a project where I'm using `cosmiconfig` to read a config file where the name was passed via the CLI's arguments (which is straightforward as the config file's name is provided via `commander`).
The problem is, applying `json-fixer` (or any sort of fixing mechanism) when `explorer.search()` is used, seems impossible as it doesn't give the name of the config is found.

I was wondering if that would be something this package could _take on board_? Or if there are ways to get the filenames from `search()` when such failures happen?

**Comment by davidtheclark** [comment]
The error message for invalid JSON should start with `JSON Error in ${filepath}`: https://github.com/davidtheclark/cosmiconfig/blob/d94bd6cd776b839c375d10846f97913b3d4e5763/src/loaders.ts#L20-L32.

Are you not seeing that message?

Test like [this](https://github.com/davidtheclark/cosmiconfig/blob/d94bd6cd776b839c375d10846f97913b3d4e5763/test/failed-files.test.ts#L32-L51) and [this](https://github.com/davidtheclark/cosmiconfig/blob/d94bd6cd776b839c375d10846f97913b3d4e5763/test/failed-directories.test.ts#L141-L167) should be confirming that that message is appearing.

**Comment by davidtheclark** [comment]
I don't think I'd like to incorporate auto-fixing into this package, but if you'd like to build an extension and link to it in the README, feel free to PR that.

**Comment by Berkmann18** [comment]
> The error message for invalid JSON should start with JSON Error in ${filepath}:

I'm aware of that and on my project (that uses this package), I have something like:
```js
if (error.name === 'JSONError') {
  const configData = readFileSync(configFromCli, 'utf-8');
  const { data, changed } = jsonFixer(configData);
  // ...
}
```
And that works, but only in the `then` chain of `explorer.load(configFromCli)`.

> Are you not seeing that message?

Yes, however, it's as accessible as getting `error.name` or `error.codeFrame` (neither of which mention the filename). I guess I'll need to use a RE approach for that (assuming the structure of the string version of the `error` won't change in the future).
