### ISSUE TITLE
Support default values

### ISSUE THREAD

**Issue by felipecrs** [davidtheclark/cosmiconfig#242]
It would be good if the users could set default values in case a value for that configuration is not found.

Something like:

```typescript
const defaultConfig = {
  "verbose": true
}

const config = cosmiconfig.search({ default: defaultConfig })
```

**Comment by davidtheclark** [comment]
I'm not sure this needs to be a feature of Cosmiconfig. Is there something challenging about applying the default values once you've loaded the config object?

**Comment by davidtheclark** [comment]
Closing because I still do not understand the difficulty that Cosmiconfig would be solving by expanding its interface in this way.
