### ISSUE TITLE
Read configuration from cosmiconfig.js(on)?

### ISSUE THREAD

**Issue by hubgit** [davidtheclark/cosmiconfig#245]
I'd quite like to move configuration for various modules out of package.json into a dedicated file, e.g. `cosmiconfig.js`/`cosmiconfig.json` - might that be possible?

**Comment by sudo-suhas** [comment]
`cosmiconfig` is used by various tools to load user configuration but the exact semantics of the file name/extension is defined by the tool itself.

For example, [`lint-staged`](https://github.com/okonet/lint-staged#configuration), apart from specifying the config in the package.json file, also respects `lint-staged.config.js`, `.lintstagedrc.js`, or `.lintstagedrc.cjs` file in JS format if present (among other file types).

So moving configuration for various modules out of package.json is not going to be possible unless the various modules are updated to respect said convention.

**Comment by hubgit** [comment]
@sudo-suhas Support for all those files comes from `cosmiconfig` though, right?

Essentially I'd like the README to change this way:

```diff
For example, if your module's name is "myapp", cosmiconfig will search up the directory tree for configuration in the following places:

* a `myapp` property in `package.json`
+ * a `myapp` property in `.cosmiconfig.json`, `.cosmiconfig.yaml`, `.cosmiconfig.yml`, `.cosmiconfig.js`, or `.cosmiconfig.cjs`
* a `.myapprc` file in JSON or YAML format
* a `.myapprc.json`, `.myapprc.yaml`, `.myapprc.yml`, `.myapprc.js`, or `.myapprc.cjs` file
* a `myapp.config.js` or `myapp.config.cjs` CommonJS module exporting an object
```

**Comment by davidtheclark** [comment]
I do not want to interject Cosmiconfig into the API of the applications that use it. It's intended to be used behind the scenes. If anybody wants to create a system like you describe, @hubgit, with a single file containing configuration for multiple applications, they could do so with a new package that uses Cosmiconfig.
