### ISSUE TITLE
Could cosmiconfig put all rc files in one folder?

### ISSUE THREAD

**Issue by adispring** [davidtheclark/cosmiconfig#248]
There are so many **rc config files in my project root folders, such as .eslintrc, .babelrc, .prettierrc, .stylelintrc, etc. These config files make my root folder a little messy.

Can cosmiconfig put all **rc files in just one folder? like node.js puts all node modules in node_modules files.

**Comment by davidtheclark** [comment]
Hi @adispring. Cosmiconfig is intended to be a behind-the-scenes library that others tools (like those you mention) can use to load configuration files, from anywhere they want to look. If those tools decide to look for configuration files in some new standard folder, as you propose, they can use Cosmiconfig to do that; but Cosmiconfig can't do it *for them*. It's up to them. So I don't think this is the place to champion a proposal like this: that would be in ESLint, Babel, Prettier, Stylelint, etc.
