### ISSUE TITLE
Synchronous API

### ISSUE THREAD

**Issue by morishitter** [davidtheclark/cosmiconfig#25]
Hi, I'm the author of stylefmt. I use rc-loader to find stylelint configration file, so it cannot match `.stylelint.config.js`.

I tried to introduce cosmiconfig, but it has only an asynchronouse API to find files. 
Do you have a plan to add synchronouse API?
If you have the plan, I can [fix this bug](https://github.com/morishitter/stylefmt/issues/81) easily :)

Thanks.

**Comment by TrySound** [comment]
Hi, @morishitter Postcss plugins should be async whenever it's possible. It's [specified in guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#22-use-asynchronous-methods-whenever-possible)

**Comment by morishitter** [comment]
@TrySound Wow, I see. I'll fix it to be as a async plugin. Thanks:)

**Comment by davidtheclark** [comment]
Ok, cool. It should be pretty straightforward to transform it into an async plugin.

**Comment by olegskl** [comment]
Putting stylelint aside, are you against a synchronous API on principle? Node and many libs on npm have sync alternatives to their async functions. I have a use case where I need to feed [babel-register](https://github.com/babel/babel/tree/master/packages/babel-register) a custom configuration and it must be done in a synchronous manner.

What do you think?

**Comment by davidtheclark** [comment]
@olegskl There's no way to accomplish what you need to *outside* of cosmiconfig code? If not, and you know a good way to accomplish the sync API, feel free to submit a PR to show some proposed code.

**Comment by olegskl** [comment]
Ok, thanks, I'll keep that in mind.

**Comment by josephfrazier** [comment]
@olegskl (or anyone else coming across this), you might be able to satisfy your use case with https://github.com/GarthDB/config-attendant, which provides a very similar API to cosmiconfig, but in a synchronous manner.
