### ISSUE TITLE
homedir is not hit?

### ISSUE THREAD

**Issue by loynoir** [davidtheclark/cosmiconfig#267]
> Cosmiconfig continues to search up the directory tree, checking each of these places in each directory, until it finds some acceptable configuration (or hits the home directory).

```sh
$ cat ~/.foorc
{"A":1}
$ cd `mktemp -d`
$ node
> const { cosmiconfigSync } = require('cosmiconfig');
> cosmiconfigSync('foo').load('.foorc')
Uncaught Error: ENOENT: no such file or directory, 
open '{{PWD}}/.foorc'
```

**Comment by d-fischer** [comment]
A directory created by `mktemp -d` is not located within the home directory, so traversing up from it will not hit the home directory.
