### ISSUE TITLE
Yarn fails to install

### ISSUE THREAD

**Issue by ChristopherBiscardi** [davidtheclark/cosmiconfig#32]
[Yarn](https://code.facebook.com/posts/1840075619545360) is a new package manager that competes with npm.

It apparently validates `engines` (on `npm install` equivalent), which cosmiconfig has [set to `4`](https://github.com/davidtheclark/cosmiconfig/blob/529cb128016f3f09bc876100b3eba2d89934da6c/package.json#L54). Since I'm on node:6, the install fails.

```
> yarn
yarn install v0.15.0
[2/4] 🚚  Fetching packages...
error cosmiconfig@2.0.1: The engine "node" is incompatible with this module. Expected version "4".
error Found incompatible module
```

 I'm happy to submit a PR for this if it's desired

**Comment by davidtheclark** [comment]
Yeah, thanks. Should be a simple PR.

**Comment by amilajack** [comment]
Fixed in https://github.com/davidtheclark/cosmiconfig/pull/33
