### ISSUE TITLE
Remove const for Safari and node.js 0.12 support

### ISSUE THREAD

**Issue by ai** [davidtheclark/cosmiconfig#35]
I saw that there is `const` in this module code. PostCSS will use `postcss-load-config`, so it will have `cosmiconf` in dependencies.

And here we have few problems:

* lack node.js 0.12 support. It is not a big deal, because it will be depreacted soon.
* lack of Safari support. Some users use PostCSS in client-side. Of course, cosmiconfig will not be *executed* in browser. But Safari will not even load JS with `const`.

Of course, we could ask client-side users to use Babel. But because problems are only with `const`, I think it is too complicated :). `var` is not so trendy, but it works and it is easy :).

@davidtheclark what do you think about it?

**Comment by davidtheclark** [comment]
@ai. Bummer. Unfortunately this will involve a lot of busywork, but probably it's worth it. Might just be a matter of replacing `const` with `var` and arrow functions with non-arrow functions.
