### ISSUE TITLE
We should promote packages like `babel` use `cosmiconfig` to load configuration

### ISSUE THREAD

**Issue by gucong3000** [davidtheclark/cosmiconfig#38]
- [ ] [eslint](https://github.com/eslint/eslint/)
- [ ] [babel-core](https://github.com/babel/babel/tree/master/packages/babel-core)
- [ ] [jshint](https://github.com/jshint/jshint)

**Comment by davidtheclark** [comment]
Closing as stale. Anybody is welcome to open issues in other projects asking if they want to use this, but it's not an issue for cosmiconfig itself.
