### ISSUE TITLE
Add ignore support

### ISSUE THREAD

**Issue by gucong3000** [davidtheclark/cosmiconfig#39]
- Configuration object field:
  `ignoreFiles` in [stylelint](http://stylelint.io/user-guide/configuration/#ignorefiles)
  `ignore` in [babel](https://babeljs.io/docs/usage/babelrc/)
- ignore configuration file:
  [.stylelintignore](http://stylelint.io/user-guide/configuration/#stylelintignore)
  [.jshintignore](http://jshint.com/docs/cli/#ignoring-files)

**Comment by davidtheclark** [comment]
Having just revamped the way that stylelint handles its ignore files, I can attest that it's unlikely to be portable from one project to another. So I think each project will have to figure out its own way.
