### ISSUE TITLE
Add support for extending configuration files.

### ISSUE THREAD

**Issue by gucong3000** [davidtheclark/cosmiconfig#40]
- http://stylelint.io/user-guide/configuration/#extends
- http://eslint.org/docs/user-guide/configuring#extending-configuration-files

**Comment by davidtheclark** [comment]
The reason extends are not part of the current API is that I suspect different projects will want to implement their own slight variations on extends, so a common implementation here would not be helpful.

If you really want to pursue this feature, we need to look in detail about how extends differ across different projects that use them, and figure out if there's enough common ground that is worth covering.

**Comment by davidtheclark** [comment]
Closing as stale.

**Comment by tomspeak** [comment]
@davidtheclark - was it ever made possible to extend a yaml configuration, like so:

```yaml
extends: ./node_modules/@module/.configrc.yml
```

**Comment by davidtheclark** [comment]
@tomspeak Nope, see reasons above.

**Comment by chrisblossom** [comment]
I've released [chrisblossom/ex-config](https://github.com/chrisblossom/ex-config) to handle the processing and extending of loaded configurations.
