### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by gucong3000** [davidtheclark/cosmiconfig#43]
```
cosmiconfig().load('/non-existent.css')
```
When we run this code. we will get a error.
```
Error: ENOENT: no such file or directory, stat '/non-existent.css'
    at Error (native)
```

Some gulp plugin will modify file extension.
Such as `gulp-stylus`, will rename `*.styl` to `*.css`.

```javascript
gulp.src([ '*.styl', '!_*.styl' ])
  .pipe(stylus(options.stylus)) // => will rename `*.styl` to `*.css`.
  .pipe(postcss(processors))  // => postcss plugin that dependence `cosmiconfig` will throw a error.
```
See: https://github.com/morishitter/stylefmt/issues/236

**Comment by davidtheclark** [comment]
This is intentional. If you have provided a file that does not exist, that is probably a mistake and you need to be informed of your mistake.

**Comment by gucong3000** [comment]
If the user run `gulp-postcss` after other gulp plugin. How to deal with this error ?
In addition, gulp will handle the error that the file does not exist.

**Comment by gucong3000** [comment]
@davidtheclark 
Like this user, what should he do?
https://github.com/morishitter/stylefmt/issues/236

**Comment by davidtheclark** [comment]
> Some gulp plugin will modify file extension.

That is a real problem, because without a real filename to start from no config will be found, and stylefmt will not run as expected — right?

(Why would the user do this anyway? What good is running stylefmt on compiled CSS?)

I do not think this is a problem for cosmiconfig, because cosmiconfig is doing exactly what it's supposed to do. stylefmt will have to figure out its own way of dealing with this — whether that's feeding cosmiconfig a different path, catching the error, etc.

**Comment by gucong3000** [comment]
@zoxon Please describe [the problems](https://github.com/morishitter/stylefmt/issues/236) you have encountered here.

**Comment by gucong3000** [comment]
@davidtheclark `postcss` or `gulp` will ensure that the CSS file does exist, and we don't necessary to check in `cosmiconfig`.

In addition, if the user is using `stylelint`, he also have same problem.

> What good is running stylefmt on compiled CSS
CSS must format befor save, and It need put configuration file to directory

**Comment by davidtheclark** [comment]
> we don't necessary to check in cosmiconfig.

I have said above and will repeat: I do not think it is a good idea for cosmiconfig to return `null` if you provide it with an explicit file name and that file does not exist. Most of the time this means you made a mistake, and you need the error to help you debug. In the rare case when it doesn't (e.g. whatever stylefmt is doing) the consumer can catch the error and handle it accordingly.
