### ISSUE TITLE
A globally-installed ESLint cannot find a locally-installed plugin

### ISSUE THREAD

**Issue by gucong3000** [davidtheclark/cosmiconfig#45]
```bash
E:\work\cosmiconfig (master) (cosmiconfig@2.1.0)
λ eslint .

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-node". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-node is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-node@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I think it's a bug: `A globally-installed ESLint cannot find a locally-installed plugin`.

If we can solve this problem in `cosmiconfig`, it might be possible to recommend` eslint` to load the configuration file with `cosmiconfig`.

**Comment by davidtheclark** [comment]
@gucong3000 I think there is very little chance that ESLint would want to switch configuration loader. I do not want to put work into it until there is a sign that they *would* be interested. If there is interest, the situation would change.

This is not an issue with cosmiconfig, and it's not a feature request that makes sense for cosmiconfig at the moment.
