### ISSUE TITLE
Silently failing

### ISSUE THREAD

**Issue by CrashyBang** [davidtheclark/cosmiconfig#49]
I have the following code block:

```js
const config = require('cosmiconfig');

const flatten = (key, source, rules) => {
    config('weblo')
        .load(null, `${process.cwd()}/package.json`)
        .then(result => {
            // Never hit
           console.log('hit');
        }).catch(err => {
            // Also never hit
            console.log(err);
        });

    // Hit straight away
    console.log( 'end');

};

module.exports = flatten;
```

If I pass anything invalid to `load()` it falls over, I have also tried passing nothing through, passing just `process.cwd()` through but ideally I do just want to read from the `package.json` hence trying to load the `configPath` as opposed to the `searchPath`. I have tried debugging but with silent output there is not too much I can do.

Sorry JS skills are a little limited so can't provide much more info.

Cheers.

**Comment by davidtheclark** [comment]
@CrashyBang What if you set the cosmiconfig options `rc: false, js: false`, then set the `searchPath` argument to `process.cwd()`? That way the only thing cosmiconfig will look for in the current working directory is `package.json`.

Right now I do not think there is not a way to specify a `package.json` as the `configPath`. PR welcome, though!

**Comment by CrashyBang** [comment]
Hey @davidtheclark thanks, well fix up `configPath` the silently failing was just me not understanding promises right so all cleared up now.
