### ISSUE TITLE
Support .config/config folder lookup

### ISSUE THREAD

**Issue by michael-ciniawsky** [davidtheclark/cosmiconfig#50]
👋 @davidtheclark 

@postcss-loader got a few requests to support setting a custom config path for `postcss.config.js` lookup and most of the folks especially wanted to store them in a separate `.config/config` folder somewhere in their project.

While thats totally fine and works for now, on the other hand it ignores/devalues the reason/benefit behind actually **autoloading** the config without the need for any additional 'setup' 😛 . So maybe there is a compromise possible to enable additional search in  `.config/config` folders while walking the file tree.

```
|– (.)config(<---)
|   |– postcss.config.js
|– client
|   |– (.)config (<---)
|   |   |– postcss.config.js 
|   |– styles
|        |– index.css (search starts here)
|        |– postcss.config.js (supported)
|– gulpfile.js
|– webpack.config.js
```

If you are basically ok with it, but don't have the time/interest to do it,  coordinating me to the location in the source for getting started would be appreciated :)

cc @ai

**Comment by ai** [comment]
I had talk with Babel developers and they didn’t like the idea @hzoo

But I think people want some solution

**Comment by michael-ciniawsky** [comment]
@ai I don't like it either 😃 , but having to give support to n 'my config is in superhacker/configs/css/postcss/config-1/postcss.config.js but it's not working' I dislike even more. That should be an omnibus compromise to folks insisting on their `.config/config` folder. We could try to ignore it 😈 , but in the issue tracker and from responses to this tweet https://twitter.com/PostCSS/status/812779937803464705 there seems to be demand for that, so maybe we shouldn't 😛

**Comment by davidtheclark** [comment]
@michael-ciniawsky I am not convinced that this feature would be valuable enough to justify additional complexity and reduced performance, for this or any other tool. People can already put configs wherever they want by specifying exactly where the config is — which is easily done. If users complain that they need to type an additional 15 characters when they set up the project, I'm not sympathetic, really. I also don't think it's the original complaint, that there are a few dotfiles in the project root, is very important. I'd much rather spend my open-source time working on something else.

**Comment by michael-ciniawsky** [comment]
@davidtheclark kk I understand, thx for quick response and clear answer

**Comment by davidtheclark** [comment]
@michael-ciniawsky This is now possible with v5, using the `searchPlaces` option. I added this use case to the examples in the readme 👍
