### ISSUE TITLE
tests fail on node v7

### ISSUE THREAD

**Issue by JaKXz** [davidtheclark/cosmiconfig#53]
https://travis-ci.org/davidtheclark/cosmiconfig/jobs/189389524

continued from https://github.com/davidtheclark/cosmiconfig/issues/48#issuecomment-270815379

**Comment by JaKXz** [comment]
FWIW @davidtheclark I probably won't be able to fix the tests as fast as you could since it's probably not an AVA issue like we're discussing in #48. I'd rather see #52 passing so that I am unblocked to fix #48. Just wanted to be up front about not being able to dedicate as much time to this as I think is necessary.

**Comment by davidtheclark** [comment]
Fixed in 836a17c252a3392e628bf1c3c3947d31475195a1. @JaKXz thanks for pointing this out. Let  me know if you run into any other problems!
