### ISSUE TITLE
Support `config` key in package.json

### ISSUE THREAD

**Issue by barraponto** [davidtheclark/cosmiconfig#56]
I know we currently support the module name directly in package.json. But I think it would make things more organized if we *also* supported by default inside of a `config` property. Like this:

```
{
  "name""soursock",
  "version": "1.0.0",
  "config": {
    "soursock": {}
  }
}
```

**Comment by davidtheclark** [comment]
I think the way this might be accomplished is to allow the [`packageProp` option](https://github.com/davidtheclark/cosmiconfig#packageprop) to be a path of dot-separated properties. In your example, it would be `packageProps: config.soursock`. Often to a PR.

**Comment by barraponto** [comment]
I see. My point is I would like to see it support both `soursock` and `config.soursock`, so you could (optionally) nest all the configuration under a the `config` key in package.json.

**Comment by davidtheclark** [comment]
@barraponto This sounds similar, then, to the question in https://github.com/davidtheclark/cosmiconfig/issues/57: Can we tweak the options so you can allow for this use-case?

**Comment by davidtheclark** [comment]
I haven't seen this pattern anywhere outside of this issue, and I don't think it's really necessary, so I'm going to close this. @barraponto, if you think of a good spec for the feature and implementation ideas, feel free to re-open.
