### ISSUE TITLE
Support hidden `.*.config.js` files

### ISSUE THREAD

**Issue by adjohnson916** [davidtheclark/cosmiconfig#57]
Support a dot prefix on `.config.js` files (similar to `.eslintrc.js` like #58).

**Comment by davidtheclark** [comment]
Can't you do this already with the `js` option?

**Comment by adjohnson916** [comment]
@davidtheclark Maybe, but can it support both hidden and not?

**Comment by davidtheclark** [comment]
I don't want to build this convention in by default, because I don't understand it's appeal and I don't think it's used outside of ESLint (right?). So the question is: how can the options change to accommodate your use-case?

**Comment by davidtheclark** [comment]
@adjohnson916: After thinking about this more, this features seems pretty unnecessary to me. The number of possible variations are endless, and I feel comfortable drawing the line around the (significant) flexibility that the package already allows. However, if you do come up with a good idea for how this could fit into cosmiconfig's options, and what implementation would look like, feel free to re-open.

**Comment by davidtheclark** [comment]
@AndersDJohnson This is now possible with v5. The `searchPlaces` option gives you enough flexibility over the names of the files that get searched.
