### ISSUE TITLE
Support `[.]*rc.js` files

### ISSUE THREAD

**Issue by adjohnson916** [davidtheclark/cosmiconfig#58]
Support `[.]*rc.js` files, like `.eslintrc.js`, with optional dot prefix like #57.

**Comment by davidtheclark** [comment]
This can already be done with the `rc` option, right?

**Comment by adjohnson916** [comment]
@davidtheclark Not sure, maybe with `rcExtensions: true`, but not sure if that can be done for both hidden and not hidden files since there's only one `rc` template?

**Comment by davidtheclark** [comment]
Closing as duplicate of #57. Let's discuss over there, as I think it's pretty much the same question.
