### ISSUE TITLE
Look in user's home even if  not in the path

### ISSUE THREAD

**Issue by sidferreira** [davidtheclark/cosmiconfig#59]
Hi! I started the following question on https://github.com/stylelint/stylelint/issues/2479 discussing about ensure that the user's home is checked for configuration files.

The scenario is the following: 
I have a 128gb mounted on my card reader. That card is never removed and that's why I place almost all my projects there. 

As it isn't mounted inside the user's home it will fail to find the configuration on the user's home.

This is a small suggestion to double check the system's path to be sure it is checked. I didn't made a PR because I'm short in time at this moment to look the best place to change the code. If you guys agree it's a good idea, you can assign it to me and I'll look for it.

**Comment by davidtheclark** [comment]
> If you guys agree it's a good idea, you can assign it to me and I'll look for it.

I think it's a good idea!

**Comment by davidtheclark** [comment]
This is possible now with the `searchPlaces` option, so the feature request should be shifted to cosmiconfig consumers (like stylelint) rather than cosmiconfig.
