### ISSUE TITLE
Document differences from rc

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#6]
- Stops at the first found, instead of finding all and merging them.
- Looks for package.json prop.
- Loads JSON, YAML, and CommonJS.
- A little more configurable (different file name expectations).
- Built-in `extends` support.
- Not as built for extension -- not such a low-level module.

Any others?

**Comment by MoOx** [comment]
Looks really good. Looking forward to it.

**Comment by davidtheclark** [comment]
Closed by ea874b9
