### ISSUE TITLE
Drop the jju package for something with a friendlier license

### ISSUE THREAD

**Issue by mgol** [davidtheclark/cosmiconfig#65]
Apparently the WTFPL license used by the `jju` ([`json-parse-helpfulerror`](https://github.com/smikes/json-parse-helpfulerror) is a minimal wrapper around `jju`) package poses some legal issues ([it's not OSI-approved](https://opensource.org/licenses/alphabetical), for example); could this dependency be swapped/dropped?

`jju` doesn't seem maintained - no updates for a year, 4 open PRs with no reply, one of them adding MIT as an option: https://github.com/rlidwka/jju/pull/24. Therefore I'm not optimistic about the `jju` situation getting resolved.

**Comment by davidtheclark** [comment]
@mgol: Happy to swap it out. Any suggestions?

**Comment by hansl** [comment]
Hi @davidtheclark,

Any reason commit https://github.com/davidtheclark/cosmiconfig/commit/836a17c252a3392e628bf1c3c3947d31475195a1 moved to from `parse-json` to `json-parse-helpfulerror`? I couldn't find a PR or any context. I understand `parse-json` is not maintained, but so is `jju` (last update 18 months ago).

I don't know the details of your project, but is the problem with `JSON.parse()` the error messages or is it `jju` more lenient in the accepted syntax? Either way I'm sure we can help :)

**Comment by davidtheclark** [comment]
@hansl: I think the reason was https://github.com/sindresorhus/parse-json/issues/6. Maybe we could go back to `parse-json` now! 

> is the problem with JSON.parse() the error messages

Yeah, the only goal with using a library here is to improve the error messages.

**Comment by hansl** [comment]
Awesome. Good to know it was fixed upstream in `parse-json`.  Do you want me to make a PR?

**Comment by davidtheclark** [comment]
@hansl: If you'd like. I'll try to get an update published this weekend.
