### ISSUE TITLE
Allow searching in `~/.config/`

### ISSUE THREAD

**Issue by vjpr** [davidtheclark/cosmiconfig#69]
The more people who use cosmiconfig, the more dot files will be littered in the home dir.

Lots of other modules place their config in `~/.config` dir, mine looks like this:

```
Autodesk
Last.fm       
QCAD            
deluge          
git             
hub             
karabiner       
menus           
sinopia         
xbuild
NuGet           
configstore            
gtk-2.0        
inkscape    
robomongo      
stetic          
yarn
```

Would be cool...

**Comment by davidtheclark** [comment]
See https://github.com/davidtheclark/cosmiconfig/issues/50#issuecomment-269242018 for my thoughts on this.

That said, I think I'm open to adding an option that specifies alternative directories to search. For your case, something like `searchIn: ['~/.config']`. `searchIn` could accept an array of paths. This way the inevitable request for a different directory, like `!/.conf`, can still be addressed.

Open to a PR.

**Comment by davidtheclark** [comment]
@vjpr: A PR to implement this could build off of https://github.com/davidtheclark/cosmiconfig/pull/61 and replace it, I think.

**Comment by davidtheclark** [comment]
This is now possible in the v5 branch by using the `searchPlaces` option.

**Comment by masaeedu** [comment]
@davidtheclark 	Sorry to be dense, but how would one use `searchPlaces` to accomplish this?

I have a file `~/.prettierrc` in my dotfiles that I'd like discovered whenever I run `prettier` in any folder on any of my machines (including directories that are not mounted under `~`). I've been looking through the docs and github issues but can't quite work it out.

Could you give me a hint on how to do this?

**Comment by olsonpm** [comment]
raise another issue @masaeedu so we don't notify everyone on this thread.

and you probably don't want to use searchPlaces for your use-case because that option is intended for listing files that should be attempted when traversing up the directories.  You should just try [loading](https://github.com/davidtheclark/cosmiconfig/blob/master/README.md#explorerload) it directly
