### ISSUE TITLE
Drop node 0.12 support?

### ISSUE THREAD

**Issue by sudo-suhas** [davidtheclark/cosmiconfig#71]
Node `v0.12.x` [reached end-of-life](https://github.com/nodejs/LTS#lts-schedule) on 2016-12-31. How about we drop support for node 0.12 and ES6ify the module?

**Comment by davidtheclark** [comment]
Yes, sounds good. Let's make Node 4 the minimum.

As part of rewriting the code, I'm interested in adding Prettier and removing stylistic rules from the ESLint config. I've had good luck using Prettier in a precommit hook (via Husky and lint-staged).

**Comment by sudo-suhas** [comment]
This is literally what I was proposing in a different issue just now. Great. I also use prettier and lint-staged for all my projects. I also like to use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) to integrate prettier and eslint.
