### ISSUE TITLE
2.2.0 possible breaks stylelint

### ISSUE THREAD

**Issue by hudochenkov** [davidtheclark/cosmiconfig#72]
Sorry, @davidtheclark, for issue like that.

I haven't investigated, but it looks like `2.2.0` breaking stylelint:

https://github.com/stylelint/stylelint/issues/2768
https://github.com/stylelint/stylelint/issues/2769

**Comment by davidtheclark** [comment]
Hm ... maybe we should do a patch fix that reverts the change to give time to investigate.

**Comment by davidtheclark** [comment]
@hudochenkov 2.2.1 is a reversion of 2.2.0. So that should fix the problem until someone can track down what went wrong.

**Comment by sudo-suhas** [comment]
@davidtheclark Any ideas on what could have gone wrong? I'll try using stylelint tomorrow but haven't used it before. So any pointers would be useful
