### ISSUE TITLE
--config cannot point to a package.json

### ISSUE THREAD

**Issue by azz** [davidtheclark/cosmiconfig#79]
Currently, if a config file is passed explicitly, and that config file is a `package.json`, the contents of the `package.json` file are loaded instead of a single property within it.

https://github.com/davidtheclark/cosmiconfig/blob/334065d9f7b557170a38b3f920bf5e90cecfab72/lib/createExplorer.js#L30-L39

Would it make sense to have a special case for `package.json` that calls `loadPackageProp` instead?

Context: https://github.com/prettier/prettier/issues/2704

**Comment by davidtheclark** [comment]
👍 from me. @sudo-suhas, agree?

**Comment by sudo-suhas** [comment]
Yes I agree too. But can we hold this off until #78 is merged? There might be conflicts and we'd have to migrate tests otherwise.

**Comment by davidtheclark** [comment]
@sudo-suhas: Yes, definitely.

**Comment by sudo-suhas** [comment]
@azz Would it be possible for you to make a PR for this change?

**Comment by azz** [comment]
Can do!
