### ISSUE TITLE
How to handle stylelint's plugins

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#8]
This is a rough one.

In order for stylelint to fully take advantage of this module, stylelint needs to be able to interpret `plugins` values in extended configs *relative to the file that references them*. This means that if Config A extends Config B, and Config B includes plugins, we can't resolve the plugins relative to Config A once everything has been merged: we have to resolve Config B's plugins as they load.

This seems like a special case ... but we really do need to enable stylelint or other modules that want similar plugin syntax to do what they want.

I see two options:

1. Build in special support for `plugins`, such that plugin resolution is done within cosmiconfig, and the resultant configuration object somehow exposes absolute paths to all plugins referenced. 
2. Expose configuration objects to transforms as they load, which I imagine would have to be done with some event-style API, e.g.
  
  ```js
  .on('load', function(result) { 
    result.config = transformConfig(result.config);
  });
  ```

Any ideas welcome.

Right now I'm kind of leaning towards option 1, because I think this feature might only be required for plugins, so why build in more flexibility than necessary.

**Comment by MoOx** [comment]
That seems to be related to `extends` which seems specific to stylelint so I am not even sure this should be in this module (I am saying that without all I need to understand, so I may say shit).
event/callback looks to be good solution to me.
But if you think a built-in solution is good, go ahead :)

ps: nice name for this module ^^

**Comment by davidtheclark** [comment]
@MoOx Yeah, I think I'm going to try taking your advice and cutting out `extends` from this module, just putting it in stylelint. cosmiconfig could still do the important work of finding and parsing the configuration files that need to be found and parsed.

**Comment by davidtheclark** [comment]
Removed extends. Leaving this to stylelint.
