### ISSUE TITLE
Branch 3.0 deleted, but no `3.0.0` version to consume

### ISSUE THREAD

**Issue by goldcaddy77** [davidtheclark/cosmiconfig#82]
Hi, one of the projects I'm working on was using an early version of the 3.0 branch and I noticed you deleted it without pushing a `3.0` tag to npm for us to consume.  When do you think this will be coming out?

**Comment by sudo-suhas** [comment]
Hey @goldcaddy77, the 3.0 branch was merged into master(#78). This was done to allow parallel work in  #80 and #81. We will be releasing `v3.0` after the integration tests have been added. While I do not have an exact timeline, we will try to release it soon. Hopefully sometime next week.

**Comment by goldcaddy77** [comment]
Gotcha, if you have a minute, would you mind leaving the 3.0 branch in place until you push 3.0.0 (i.e. create branch `3.0` off of `6eb3cc85d3a435e6b9e252b341e601960312f410` again)?

**Comment by sudo-suhas** [comment]
@goldcaddy77 cosmiconfig 3.0 has been released to npm.
