### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/cosmiconfig#84]
@sudo-suhas How do you feel about adding Flow types? 

I was thinking about adding JSDoc-style comments to more of the functions, but that got me thinking that adding Flow types would both document functions _and_ help with type safety. Type checking might be especially helpful now that we have a bunch of functions that sometimes return Promises, sometimes don't.

If you aren't opposed, I could do that at some point today so we can include it in the 3.0 release.

**Comment by sudo-suhas** [comment]
Honestly not sure. Haven't used it myself and that could be the reason I find it harder to read code with flow. Example - https://github.com/Thinkmill/jest-in-case/blob/master/index.js. 

Couple of questions. Would this add a transpilation step? If we want type checking, should we consider typescript?

**Comment by davidtheclark** [comment]
> Would this add a transpilation step?

We could use comments, like your example, or add a build step — change `lib/` to `src/`, use `flow-remove-types` to create a `dist/` directory that is ignored by Git but included in the npm package. If we're going to do it, I'd prefer the build step so we don't have to use comments for types.

> If we want type checking, should we consider typescript?

I haven't used Typescript much, and am not really interested because Flow has worked well for me.

**Comment by sudo-suhas** [comment]
The advantage of documentation with type checking is certainly worth having. :+1: from me. Is there any advantage to doing the refactoring before release?

**Comment by davidtheclark** [comment]
@sudo-suhas: The advantage to doing it before the release is that it may involve some refactoring, and will involve a build process, so if we accidentally break something we have a major change to hide behind. But it should be fine, really. 

If you're interested, I can try to do it later today. I'll pledge to release v3 before I go to sleep tonight — so if I can't finish Flow types before then, we can leave them out of the release.

**Comment by sudo-suhas** [comment]
Ha ha.. A few days are not gonna make any real difference. Considering that this would change the file structure for package the end-user gets, certainly better to do it in a major version release. Please take your time. If this is a big enough task, I would be happy to share some of the work load.

**Comment by davidtheclark** [comment]
Ok, I will take my time :)

**Comment by azz** [comment]
An unfortunate side-effect of this is that other libs (like prettier) can no longer follow the master branch of this library by installing from github. We have to wait for npm releases. Was this intentional?

**Comment by davidtheclark** [comment]
@azz I don't have any reason for blocking that kind of workflow. It's unfortunate. I don't know of any way to use Flow or Babel or any compilation step without causing this. I'd love suggestions if anybody knows a better way!

So the only solution I know of would be to remove Flow types. I hesitate to do that, though, unless there are strong arguments for allowing/encouraging users to pin to the master branch. @azz can you explain why you think that's important? (If it's only for experiments and trial runs, I don't think it's too much of a pain to `cd node_modules/cosmiconfig && npm install && npm build && cd -` as needed, right?)

**Comment by sudo-suhas** [comment]
@davidtheclark One solution which could work is to remove `dist` from `.gitignore`. But I don't think we should do this unless there is a very good reason.

**Comment by ikatyang** [comment]
The easiest way is to set up a deploy script on travis, something like: `npm build` + `git push` to another branch (e.g. `dist`).

I think what @azz mean is to have something like [nightly build](https://www.typescriptlang.org/docs/handbook/nightly-builds.html) (installed from github is enough) so that users won't have to wait for a long time just for a bug fix that had already merged in master, and it's impossible to ask users to run `cd node_modules/xxx && npm install && ...` manually, we can't control our dependency unless we fork it.

**Comment by sudo-suhas** [comment]
Another solution would be to use `semantic-release`. That way changes would be released as soon as they made it to master.

**Comment by davidtheclark** [comment]
I think a nightly build would be overkill for this library, which has been very stable for quite some time. I'd prefer to just release bug fixes quickly. The particular situation we have right now, with v3, is a significant exception to the norm. Normally, I hope there is no need to pin to master, and I would not in fact want to encourage people to do that.

**Comment by ikatyang** [comment]
I mean something like nightly build but only deploy on another github branch, which is still considered not stable. Just a way to get some bug fixes quickly. 😅

**Comment by azz** [comment]
Quick patches or semantic releases are both great solutions.
